### PR TITLE
[ONNX FE] Update ONNX submodule to v1.22.0

### PR DESCRIPTION
**Pull request by mvafin**
### Details

Bumps the bundled ONNX submodule from **v1.18.0 → v1.22.0**.

### Key finding: no protobuf upgrade / no Abseil needed

The concern going in was that a newer ONNX would force a protobuf upgrade (to ≥4.22), which in turn would drag in **Abseil** as a mandatory new third-party dependency for the default (bundled, static, `-fPIC`) build.

This turns out **not** to be required. ONNX 1.22.0 builds and links cleanly against the existing bundled **protobuf 21.12** (libprotobuf 3.21.12):

- OpenVINO supplies its own `protoc`/`libprotobuf` to ONNX via `ONNX_CUSTOM_PROTOC_EXECUTABLE` (set in `thirdparty/onnx/CMakeLists.txt`), so ONNX's internal `protobuf>=4.22 ⇒ find_package(absl)` / FetchContent path is never taken.
- All ONNX CMake options OpenVINO passes (`ONNX_USE_LITE_PROTO`, `ONNX_ML`, `ONNX_NAMESPACE`, `ONNX_CUSTOM_PROTOC_EXECUTABLE`, `ONNX_USE_PROTOBUF_SHARED_LIBS`) still exist and behave the same in 1.22.
- ONNX 1.22 `.proto` sources are still proto2 and are regenerated fine by protoc 21.12.

### Local verification (Linux, GCC 11.4, Release)

- `openvino_onnx_frontend`, `openvino_tensorflow_frontend`, `openvino_paddle_frontend` — all compile and link with **zero errors** against bundled protobuf 21.12.
- `libonnx.a` / `libonnx_proto.a` report version **1.22.0**, linked against `libprotobuf-lite.a` (3.21.12).
- `ov_onnx_frontend_tests` (`INTERPRETER.*`): **932 passed, 0 failed, 5 skipped** (pre-existing skips).

### Tickets
 - *CVS-188701*

### CODE REVIEW

**Comment by mvafin** [comment]
## RISC-V (RVV 1.0) cross-build failure — fixed in 769af87

The RVV cross-build failed at Ninja graph-load time:

```
ninja: error: 'thirdparty/protobuf/install/bin/protoc', needed by
'.../onnx_openvino_onnx-ml.proto', missing and no known rule to make it
```

**Root cause:** ONNX 1.22 adds the imported `protobuf::protoc` target to the `DEPENDS` of its proto-generation custom commands (it was `DEPENDS ${INFILE}` only in 1.18). On cross-compilation, OpenVINO supplies `protoc` as an **IMPORTED** executable backed by the `host_protoc` ExternalProject. CMake lowers an imported-executable dependency to a **file-level** dependency on its `IMPORTED_LOCATION` (`thirdparty/protobuf/install/bin/protoc`). Since that ExternalProject declared no `BUILD_BYPRODUCTS`, Ninja had no rule producing the path → hard error. Native builds are unaffected (they use the real `protoc` target via `PROTOC_DEPENDENCY`).

**Fix:** add an optional `BUILD_BYPRODUCTS` argument to `ov_native_compile_external_project()` and declare the host protoc binary as a byproduct.

**Verification:** reproduced the exact error locally by forcing the host-protoc path on a native build (removing `BUILD_BYPRODUCTS` → identical `missing and no known rule` error); with the fix the host protoc builds (`protoc-3.21.12.0`), the `.proto`/`.pb.cc` files generate, and `libonnx_proto.a` links cleanly.

**Comment by mvafin** [comment]
## RHEL 8.10 build failure — fixed in 490b852

```
onnx/defs/sequence/utils.cc:149: error: cannot deduce template arguments for 'not_equal_to' from ()
onnx/defs/sequence/defs.cc:77:  error: cannot deduce template arguments for 'not_equal_to' from ()
```

(The `cuInit ... CUDA error` lines in the same log are unrelated environment noise.)

**Root cause:** ONNX 1.22's own source calls `std::adjacent_find(..., std::not_equal_to())`. Bare `std::not_equal_to()` relies on CTAD for a class template whose only parameter is defaulted (`template<class T = void>`) and which has no deduction guide. Newer libstdc++/GCC tolerate it, but RHEL 8.10's older gcc-toolset correctly rejects it. This is a hard error (deduction failure), so compiler flags cannot work around it — the source must be fixed. Still unfixed upstream (incl. `main`).

**Fix:** `thirdparty/onnx/patches/not_equal_to_ctad.patch` rewrites the two call sites to `std::not_equal_to<>()` — the standard transparent comparator, semantically identical and valid on all C++17 compilers. OV's `thirdparty/onnx/CMakeLists.txt` now applies any `patches/*.patch` idempotently at configure time (via `git apply`, with a `--reverse --check` guard) before `add_subdirectory`. Stop-gap until upstreamed to ONNX.

**Verification (local):** patch applies and is idempotent across re-configures ("already applied"); the two previously-failing TUs (`sequence/utils.cc`, `sequence/defs.cc`) and the full `onnx` target compile. Note: my local GCC 11.4 accepts *both* forms, so this couldn't reproduce the RHEL rejection directly — but `std::not_equal_to<>()` is unambiguously valid C++14+, so it removes the toolchain-version dependency that caused the failure.

**Comment by mvafin** [comment]
## clang-format failure — fixed in 86b037c

The code-style job didn't flag a real formatting issue. Its reviewdog step diffs the whole working tree and caught the ONNX submodule reporting as dirty:

```
thirdparty/onnx/onnx:1:+Subproject commit 2bb50465112feca9003e1ed654d77f01ff1415ca-dirty
```

**Cause:** the `not_equal_to` patch (490b852) modifies files *inside* the ONNX submodule working tree at configure time, so the submodule becomes `-dirty`.

**Fix:** add `ignore = dirty` to the `thirdparty/onnx` entry in `.gitmodules`, matching the existing oneDNN / xbyak / zlib submodules. The commit pointer is still tracked; only working-tree dirtiness is ignored. Verified locally: with the submodule patched, a plain `git diff` no longer reports the `-dirty` subproject change.

**Comment by mvafin** [comment]
## Python `onnx` bumped to 1.22.0 + test adaptation — fad6a3a

Aligned the Python `onnx` pin with the C++ submodule (both 1.22.0) and adapted the ONNX FE Python tests. **Verified locally against onnx 1.22.0 on CPU** by building the OV Python bindings + ONNX FE + CPU plugin and running the suite in an onnx-1.22 venv.

### onnx 1.22 Python API breakages fixed (these blocked collection entirely)
| File | Change in onnx 1.22 | Fix |
|---|---|---|
| `runtime.py` | `float32_to_float8e5m2/e4m3`, `float8*_to_float32` removed from `onnx.helper`/`numpy_helper` | fall back to `ml_dtypes` (a 1.22 dep) |
| `test_ops_unary.py`, `test_ops_random.py` | `onnx.mapping` module removed | drop the (unused) import |
| `test_frontend_onnx.py` | `make_attribute` rejects Python `bool` in an INTS field | build `attribute_list_bool` as ints |

### New opset 24-27 surface — marked xfail with reasons (189 tests)
- **New ops, not yet in OV ONNX FE:** LinearAttention-27 (28), CausalConvWithState-27 (13), FlexAttention preview (11), BitCast-26 (10), CumProd-26 (9), TensorScatter-24 (3), some Attention-24 (2)
- **New sub-byte / float8 dtypes** in Cast/CastLike/Quantize (INT2/UINT2, INT4/UINT4, FLOAT4E2M1, FLOAT8E8M0, FLOAT8E\*FNUZ) — 82
- **Reference/accuracy changes** exposed by 1.22 (Cast inf-vs-FLT_MAX saturation, DFT rfft/irfft, NMS boundary, Range bf16) — 31

### Also
- `test_qlinearmatmul_2D_int8_float16/float32` now **pass** on 1.22 → removed their stale strict xfails (issues 139937/139938).

**Result:** full ONNX FE Python suite (excl. model-zoo / real-model / CUDA) = **1635 passed, 473 xfailed, 0 failed**.

Note: the xfails are `strict=True` (repo default), so when OV later implements any of these ops/dtypes the strict-XPASS will flag the marker for removal. Follow-up tickets should be filed to implement the new opset-24-27 operators; the xfail reasons name each op.

**Comment by mvafin** [comment]
## Conan: dropped the onnx requirement — 4e74f68

The Conan build pinned `onnx/1.18.0`, which blocked the 1.22 bump:
- **Conan Center Index has no onnx 1.22.0** (latest recipe is 1.20.1).
- Any CCI onnx **> 1.18.0** hard-requires `protobuf/[>=4.25.3 <7]` **+ abseil**, which conflicts with the Conan build's `protobuf/3.21.12` pin and would force the protobuf-5.x / Abseil migration through the Conan path.

**Fix:** removed `onnx/1.18.0` from `conanfile.txt`. In [thirdparty/dependencies.cmake](https://github.com/openvinotoolkit/openvino/blob/master/thirdparty/dependencies.cmake) the ONNX selection is:
```cmake
find_package(ONNX 1.16.2 QUIET COMPONENTS onnx onnx_proto NO_MODULE)
if(ONNX_FOUND)  # conan/vcpkg package
   ...
else()
   add_subdirectory(thirdparty/onnx)  # bundled submodule
endif()
```
With no onnx in `conanfile.txt`, Conan (CMakeDeps) generates no ONNX config package, `find_package(ONNX ... NO_MODULE)` fails, and the build falls back to the **bundled 1.22.0 submodule** — the same path already proven to build against protobuf 3.21.12.

**Benefits:** no dependency on onnx 1.22 landing in CCI; no protobuf-5.x/abseil pulled into the Conan graph; Conan's ONNX stays automatically in lockstep with the submodule.

**To verify in CI:** the RISC-V Conan job ([linux_riscv_conan.yml](https://github.com/openvinotoolkit/openvino/blob/master/.github/workflows/linux_riscv_conan.yml)) builds with `ENABLE_SYSTEM_PROTOBUF=ON` (Conan protobuf 3.21.12) + now-bundled onnx. This is a cross-compile, so it exercises the host-protoc path fixed earlier (BUILD_BYPRODUCTS). `thirdparty/onnx/CMakeLists.txt` already guards the protobuf export with `if(NOT ENABLE_SYSTEM_PROTOBUF ...)`, so the system-protobuf + bundled-onnx combination is anticipated.

Note: `vcpkg.json` still lists onnx separately; leaving that untouched for now (vcpkg version availability differs).

File: thirdparty/onnx/CMakeLists.txt [hunk 1]
```diff
@@ -8,6 +8,45 @@
...
+# "cannot deduce template arguments for 'not_equal_to' from ()". The patch
+# rewrites it to the portable 'std::not_equal_to<>()'. Newer compilers accept
+# the upstream source as-is, so the patch is only needed for GCC < 9 and is
+# gated accordingly to avoid modifying the submodule working tree elsewhere.
+# Patches are applied idempotently so re-configuration and incremental builds
+# are safe.
+if(CMAKE_CXX_COMPILER_ID STREQUAL "GNU" AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9)
+    find_package(Git QUIET)
+    if(GIT_FOUND)
+        file(GLOB _onnx_patches "${CMAKE_CURRENT_SOURCE_DIR}/patches/*.patch")
```
Comment (praasz) [inline thirdparty/onnx/CMakeLists.txt]: Don't use glob it will abandon in the project.

Make explicit list of patch files (conditional add e.g. by genex) that will give better control of what patch file will be added in what gcc, OS etc version.

Add information when it can be removed and patches should be avoided. e.g. when GCC 8 support will be droped.

Comment (mvafin) [reply thirdparty/onnx/CMakeLists.txt]: Done in 225838e. Replaced `file(GLOB)` with an explicit patch list (`not_equal_to_ctad.patch`), and added a TODO documenting that the patch should be removed once GCC 8 support is dropped or the fix is upstreamed into the pinned ONNX version. The patch is also gated to GCC < 9 so it only touches the submodule on that toolchain.

**Review by bumbosiepsak — APPROVED** [review]
Approved with a remark, that:
- patching is unavoidable if we want to keep RHEL8 support
- patching is a good tactical solution if we want to drop RHEL8 support or equip it with an updated/backported GCC
  - we will do it for `2026.3` (and patching will be just a quick stint)
  - it will unlock early feature development for `2026.3`
- this still needs Protobuf in (at least) version `4.25.3` to be correct (now it works by sheer luck).

**Review by olpipi — APPROVED** [review]

**Comment by mvafin** [comment]
ONNX tests in Jenkins fail with
> Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from /home/jenkins/agent/workspace/private-ci/ie/e2e-tests-linux-ubuntu22-layer/b/install/dldt_cpack/tests/layer_tests/common/out/CPU_test_add_precommit9x6o86vr/model.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model.cc:181 onnxruntime::Model::Model(onnx::ModelProto&&, const onnxruntime::PathString&, const onnxruntime::IOnnxRuntimeOpSchemaRegistryList*, const onnxruntime::logging::Logger&, const onnxruntime::ModelOptions&) Unsupported model IR version: 13, max supported IR version: 11

We need to update onnxruntime

**Review by praasz — APPROVED** [review]
