### ISSUE TITLE
[Bug] Fails to build with LTO enabled

### ISSUE THREAD

**Issue by dbermond** [openvinotoolkit/openvino#9476]
##### System information (version)
- OpenVINO => git master
- Operating System / Platform => Arch Linux x86_64
- Compiler => gcc 11.1.0
- Problem classification: build error
- Framework: not applicable
- Model name: not applicable

##### Detailed description
I'm getting the following build error when enabling LTO on git master:

```
/usr/bin/ld: /tmp/ccFXmYMq.ltrans11.ltrans.o: in function `dnnl::impl::md2fmt_str[abi:cxx11](dnnl_memory_desc_t const*)':
<artificial>:(.text._ZN4dnnl4impl10md2fmt_strB5cxx11EPK18dnnl_memory_desc_t+0xd6): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
/usr/bin/ld: <artificial>:(.text._ZN4dnnl4impl10md2fmt_strB5cxx11EPK18dnnl_memory_desc_t+0x35d): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
/usr/bin/ld: /tmp/ccFXmYMq.ltrans11.ltrans.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > dnnl::impl::(anonymous namespace)::init_info_convolution<dnnl::impl::convolution_pd_t>(dnnl_engine const*, dnnl::impl::convolution_pd_t const*)':
<artificial>:(.text._ZN4dnnl4impl12_GLOBAL__N_1L21init_info_convolutionINS0_16convolution_pd_tEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPK11dnnl_enginePKT_+0x9c3): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
/usr/bin/ld: /tmp/ccFXmYMq.ltrans11.ltrans.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > dnnl::impl::(anonymous namespace)::init_info_inner_product<dnnl::impl::inner_product_pd_t>(dnnl_engine const*, dnnl::impl::inner_product_pd_t const*)':
<artificial>:(.text._ZN4dnnl4impl12_GLOBAL__N_1L23init_info_inner_productINS0_18inner_product_pd_tEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPK11dnnl_enginePKT_+0x360): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
/usr/bin/ld: /tmp/ccFXmYMq.ltrans11.ltrans.o: in function `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > dnnl::impl::(anonymous namespace)::init_info_matmul<dnnl::impl::matmul_pd_t>(dnnl_engine const*, dnnl::impl::matmul_pd_t const*)':
<artificial>:(.text._ZN4dnnl4impl12_GLOBAL__N_1L16init_info_matmulINS0_11matmul_pd_tEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPK11dnnl_enginePKT_+0x38d): undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const'
/usr/bin/ld: /tmp/ccFXmYMq.ltrans11.ltrans.o:<artificial>:(.text._ZN4dnnl4impl12_GLOBAL__N_1L17init_info_poolingINS0_12pooling_pd_tEEENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPK11dnnl_enginePKT_+0x6d9): more undefined references to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_high_mark() const' follow
collect2: error: ld returned 1 exit status
make[2]: *** [src/plugins/intel_gpu/CMakeFiles/ov_intel_gpu_plugin.dir/build.make:1266: /build/openvino-git/src/openvino/bin/intel64/Release/lib/libov_intel_gpu_plugin.so] Error 1
```

- complete build log if needed: https://paste.ee/p/CbRho
- disabling LTO on git master makes it to build fine (problem seems to be LTO-related)
- latest stable version 2021.4.2 builds fine with LTO enabled
- commit f565e0f854 (from 2 days ago) was building fine with LTO enabled
- a git bisect shows the offending commit as 3ee00e018a66ffb452a24a60f2c291cd2da43a5e

##### Steps to reproduce

Build openvino git master on Arch Linux with:

```
$ cmake -B build -S openvino \
        -DBUILD_TESTING:BOOL='OFF' \
        -DCMAKE_BUILD_TYPE:STRING='Release' \
        -DCMAKE_INSTALL_PREFIX:PATH='/opt/intel/openvino' \
        -DENABLE_AVX512F:BOOL='OFF' \
        -DENABLE_PROFILING_ITT:BOOL='OFF' \
        -DENABLE_PYTHON:BOOL='ON' \
        -DENABLE_OPENCV:BOOL='OFF' \
        -DENABLE_CLANG_FORMAT:BOOL='OFF' \
        -DENABLE_NCC_STYLE:BOOL='OFF' \
        -DENABLE_SYSTEM_PROTOBUF:BOOL='ON' \
        -DENABLE_LTO:BOOL='ON' \
        -DTREAT_WARNING_AS_ERROR:BOOL='OFF' \
        -Wno-dev
$ make -C build
```

##### Issue submission checklist

 - [X] I report the issue, it's not a question
   
 - [X] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [X] There is reproducer code and related data files: images, videos, models, etc.

**Comment by Iffa-Meah** [comment]
I have cross-checked your OS with the[ official OpenVINO documentation](https://docs.openvino.ai/latest/openvino_docs_install_guides_installing_openvino_linux.html#system-requirements) and [official OpenVINO GitHub wiki](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux).
According to these documentations, please note that Arch Linux is not officially validated/supported by OpenVINO. Hence, the use of OpenVINO with this system might or might not work.

I tested your build command on a **supported OS (Ubuntu 18.04)**. No issue was found when the LTO was enabled.
![ubuntu_success1](https://user-images.githubusercontent.com/79643476/147809830-6845b812-2246-49d1-affb-d3fe356d7bd2.png)

![ubuntu_success2](https://user-images.githubusercontent.com/79643476/147809861-dae6e0d3-4305-4b4e-99c6-ad72f7875714.png)

This issue seems to be specific to Arch Linux. 
We'll look further into this and get back to you soon.

**Comment by dbermond** [comment]
Thank you for the reply.

**Comment by avitial** [comment]
@dbermond apologies for the delay, I was able to build OpenVINO successfully on Arch Linux with LTO enabled on master branch (from yesterday, commit e89db1c) without any issues. Could you try on latest master branch and check whether the build issue is still present?

Best Regards,
Luis

**Comment by dbermond** [comment]
Thank you for the reply @avitial.

I still cannot build it using the latest git master when enabling LTO with the above options. Getting the same link error at the very end of the build process. Tried a lot of things, like changing some CMake options, disabling all the build flags, but still not working for me. Building without LTO works fine.

If it works for you, fell free to close this issue. Maybe I'm missing something? Curiously, LTO builds were working fine for me a few commits ago, and I even could bisect the supposed offending commit.

**Comment by avitial** [comment]
@dbermond I wasn't able to reproduce the issue with LTO enabled before (tried on Ubuntu 20.04 and Arch Linux) but interestingly enough I now can see the error on Arch Linux. Looks like the problem might come from onednn for GPU, try disabling with `-DENABLE_ONEDNN_FOR_GPU:BOOL='OFF'` and see if LTO builds successfully for you on Arch Linux. Let me know the outcome of this and if this solution works for you.

Best Regards,
Luis

**Comment by dbermond** [comment]
I can confirm that current git master builds fine with LTO enabled when using `-DENABLE_ONEDNN_FOR_GPU:BOOL='OFF'`. When removing this option, it fails to build as reported above.

It looks like that this option is related to the commit identified as the offending one in my git bisect.

**Comment by avitial** [comment]
I couldn't reproduce the reported issue on the validated OS (Ubuntu* 20.04 (64-bit) with default GCC* 9.3.0). If you need to build with LTO enabled I'd suggest switching to a validated operating system. Kindly refer to the [build instructions for Linux](https://github.com/openvinotoolkit/openvino/wiki/BuildingForLinux ) for a list of validated operating systems for Linux builds.
