### ISSUE TITLE
 Object Detection Model Serving Not Working in OpenVINO

### ISSUE THREAD

**Issue by dsnsabari** [openvinotoolkit/openvino#25110]
### OpenVINO Version

**openvino 2024.2.0**

### Operating System

Windows System

### Device used for inference

CPU

### Framework

PyTorch

### Model used

Yolov8 and Yolov10

### Issue description

The YOLOv8 and YOLOv10 models were trained using the Ultralytics Python package. The YOLOv8 model serving worked with the **OpenVINO-dev[ONNX]==2022.3.1** version and is currently in production. However, the **new (openvino 2024.2.0)** OpenVINO model serving is not working and throws the following error. I have attached the model and code file.

### Step-by-step reproduction

```bash

import ipywidgets as widgets
import openvino as ov

core = ov.Core()

device = widgets.Dropdown(
    options=core.available_devices + ["AUTO"],
    value="AUTO",
    description="Device:",
    disabled=False,
)

# device

converted_model_path = "./yolov8n_openvino_model/"

# Read the network and corresponding weights from a file.
model = core.read_model(model=converted_model_path)
# Compile the model for CPU (you can choose manually CPU, GPU etc.)
# or let the engine choose the best available device (AUTO).
compiled_model = core.compile_model(model=model, device_name=device.value)

# Get the input and output nodes.
input_layer = compiled_model.input(0)
output_layer = compiled_model.output(0)

# Get the input size.
height, width = list(input_layer.shape)[1:3]
```
[yolov10n_openvino_model.zip](https://github.com/user-attachments/files/15894724/yolov10n_openvino_model.zip)

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\objectdetection\yolo_format\predict_new_openvinomodel.py", line 27, in <module>
    model = core.read_model(model=converted_model_path)
  File "C:\Users\sabar\anaconda3\envs\new_pytorch\lib\site-packages\openvino\runtime\ie_api.py", line 502, in read_model
    return Model(super().read_model(model))
RuntimeError: Exception from src/inference/src/cpp/core.cpp:90:
Exception from src/inference/src/model_reader.cpp:160:
Unable to read the model: D:/objectdetection/yolo_format/yolov8n_openvino_model/ Please check that model format: D:/objectdetection/yolo_format/yolov8n_openvino_model/ is supported and the model is correct. Available frontends: ir onnx paddle pytorch tf tflite
```

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by mlukasze** [comment]
thanks for letting us know
Could you share a model?
Could you try 2024.2 version to compare behavior? 
Are you trying to import pytorch model (as report states), or converted to ONNX (by the code)?

cc/ @AKochin

**Comment by dsnsabari** [comment]
@mlukasze , Please find the model. [yolov10n_openvino_model.zip](https://github.com/user-attachments/files/15894724/yolov10n_openvino_model.zip) I am trying to infer the openvino model which is converted from pytorch model. I am facing issue in **2024.2** version.

**Comment by mlukasze** [comment]
thanks for the explanation, our engineers will look at your problem in first possible moment.
we will back to you

**Comment by andrei-kochin** [comment]
@dsnsabari according to the code snippet provided and to the error you see you are trying to feed the read_model call  the directory instaead of the IR *.xml file which is not expected. Was this code really working fine with 22.3?

**Comment by dsnsabari** [comment]
@andrei-kochin , I am not using this code to read the model in the 22.3 version. Could you share the sample script for serving the open vino model in the latest package?

**Comment by andrei-kochin** [comment]
@dsnsabari I'm not the expert in serving but I definitely can say that your code fore read_model should look like this to work:

```python
converted_model_path = "./yolov8n_openvino_model/yolov8n.xml"

# Read the network and corresponding weights from a file.
model = core.read_model(model=converted_model_path)
```

Or you even can skip read_model and feed it directly to the compile_model():
```python
converted_model_path = "./yolov8n_openvino_model/yolov8n.xml"

# Compile the model for CPU (you can choose manually CPU, GPU etc.)
# or let the engine choose the best available device (AUTO).
compiled_model = core.compile_model(model=converted_model_path, device_name=device.value)
```

**Comment by dsnsabari** [comment]
@andrei-kochin , Thank you so much. I want to set the config parameters below while initializing the model.  "AttributeError: 'Core' object has no attribute 'set_config'"

```bash

#config = {"CPU_THREADS_NUM": "2", "CPU_BIND_THREAD": "YES"}
core.set_config({"CPU_THREADS_NUM": "2", "CPU_BIND_THREAD": "YES"}, "CPU")

```

**Comment by andrei-kochin** [comment]
@dsnsabari new call is the set_property. Please see the [doc reference](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device.html#read-write-properties).

Some examples can be found [here](https://docs.openvino.ai/2024/openvino-workflow/running-inference/inference-devices-and-modes/cpu-device/performance-hint-and-thread-scheduling.html#multi-threading-optimization).

**Comment by dsnsabari** [comment]
@andrei-kochin thank you so much.
