### ISSUE TITLE
[Bug]: Quantized model does not compile for device type=NPU

### ISSUE THREAD

**Issue by shashichilappagari** [openvinotoolkit/openvino#22846]
### OpenVINO Version

2023.3

### Operating System

Other (Please specify in description)

### Device used for inference

NPU

### Framework

None

### Model used

yolov8

### Issue description

We are trying to run quantized models on the latest Meteor Lake CPUs, specifically on the built-in NPU. We are using Ubuntu 22.04.

We are able to run:

1. Floating point models on CPU
2. Quantized models on CPU
3. Floating point models on NPU

However, we are unable to run quantized models on NPU. The `compile_model` method throws an error. 

### Step-by-step reproduction

Here is the code that can reproduce the error:

This part of the code defines all the variable needed.
``` python
original_model_path = '<enter the path to a float onnx model>'
calibration_images_path = '<enter the path to a folder of images that can be used for calibration>'
image_height = 640
image_width = 640



```

This part of the code defines the functions to quantize an ONNX model
``` python
import os
import nncf
import openvino.runtime as ov
import numpy as np
import cv2 as cv
from openvino.runtime import serialize

class ImageLoader():
    """ Loads images from a folder """
    def __init__(self, dataset_path, image_height, image_width):
        # Use OpenCV to gather image files
        # Collect names of image files
        self._files = []
        all_files_in_dir = os.listdir(dataset_path)
        for name in all_files_in_dir:
            file = os.path.join(dataset_path, name)
            if cv.haveImageReader(file):
                self._files.append(file)

        # Define shape of the model
        self._shape = (image_width,image_height)

    def __len__(self):
        """ Returns the length of the dataset """
        return len(self._files)

    def __getitem__(self, index):
        """ Returns image data by index in the NCHW layout
        Note: model-specific preprocessing is omitted, consider adding it here
        """
        if index >= len(self):
            raise IndexError("Index out of dataset size")

        image = cv.imread(self._files[index]) # read image with OpenCV
        image = cv.resize(image, self._shape) # resize to a target input size
        image = np.expand_dims(image, 0)  # add batch dimension
        image = image.transpose(0, 3, 1, 2)  # convert to NCHW layout
        return image, None   # annotation is set to None


def transform_fn(data_item):
    images = data_item[0]
    images = images / 255
    return images

def openvino_ir_quantize(model_name, calib_path, image_height, image_width):
    data_loader = ImageLoader(calib_path, image_height=image_height, image_width=image_width)
    nncf_calibration_dataset = nncf.Dataset(data_loader, transform_fn)
    model = ov.Core().read_model(model_name)

    quantized_model = nncf.quantize(model, nncf_calibration_dataset)

    serialize(quantized_model, model_name.split("/")[-1].split(".")[0] + "_int8.xml")
    return model_name.split("/")[-1].split(".")[0] + "_int8.xml"
```

This part of the code quantizes the model
``` python
model_name = openvino_ir_quantize(
    original_model_path, calibration_images_path, image_height, image_width)
print(model_name)
```

This part of the code prints the available devices. When run on a Meteor Lake CPU, we should see ['CPU', 'GNA', 'NPU']
``` python
import openvino
core = openvino.Core()
print(core.available_devices)
```
This part of the code compiles the model for NPU and produces the following error.

```
error: FeasibleAllocation failed : Scheduler failure, cannot schedule anything and there is no buffer to spill

[ GENERAL_ERROR ] Exception from src/vpux_plugin/src/plugin.cpp:432:
LevelZeroCompilerInDriver: Failed to compile network. Error code: 2147483646. Compilation failed
Failed to create executable"
```

``` python
model = core.read_model(model=model_name)
npu_compiled_model = core.compile_model(model=model, device_name='NPU')
```

This part of the code compiles for CPU and does not throw any error.

``` python
cpu_compiled_model = core.compile_model(model=model, device_name='CPU')
```
Below you can find the onnx file (in zip file) and sample calibration data (20 images picked from coco dataset, but you can use any folder of images).
[yolov8n_relu6_face--640x640_float_openvino_npu_1.zip](https://github.com/openvinotoolkit/openvino/files/14290264/yolov8n_relu6_face--640x640_float_openvino_npu_1.zip)
[calibration_data.zip](https://github.com/openvinotoolkit/openvino/files/14290172/calibration_data.zip)

### Relevant log output

```shell
error: FeasibleAllocation failed : Scheduler failure, cannot schedule anything and there is no buffer to spill

[ GENERAL_ERROR ] Exception from src/vpux_plugin/src/plugin.cpp:432:
LevelZeroCompilerInDriver: Failed to compile network. Error code: 2147483646. Compilation failed
Failed to create executable"
```

### Issue submission checklist

- [X] I'm reporting an issue. It's not a question.
- [X] I checked the problem with the documentation, FAQ, open issues, Stack Overflow, etc., and have not found a solution.
- [X] There is reproducer code and related data files such as images, videos, models, etc.

**Comment by abotsiev** [comment]
@shashichilappagari can you please try with the latest NPU driver (includes the latest and greatest public compiler version) available at https://www.intel.com/content/www/us/en/download/794734/intel-npu-driver-windows.html? The problem should be fixed there already.

**Comment by shashichilappagari** [comment]
@abotsiev Thanks for the information. But we are working on Ubuntu22.04. I am not sure we can use this. Is there a version available for Ubuntu22.04?

**Comment by ilya-lavrenov** [comment]
> @abotsiev Thanks for the information. But we are working on Ubuntu22.04. I am not sure we can use this. Is there a version available for Ubuntu22.04?

Latest available driver for Ubuntu 22.04 https://github.com/intel/linux-npu-driver/releases/tag/v1.1.0

**Comment by shashichilappagari** [comment]
@ilya-lavrenov Thanks. We are actually using this driver. Were you able to run the code I provided and see that it compiles for NPU?

**Comment by dmatveev** [comment]
@abotsiev @PatrikStepan @ArtemySkrebkov E112726

**Comment by shashichilappagari** [comment]
@ilya-lavrenov @abotsiev An update from our side: we tried OpenVINO on Windows with the latest driver you pointed out and we still were unable to compile the model. We just see the following error message:
```
[ GENERAL_ERROR ] Exception from src/vpux_plugin/src/plugin.cpp:432:
LevelZeroCompilerInDriver: Failed to compile network. Error code: 2147483646. Compilation failed
Failed to create executable"
```

**Comment by hbalasu1** [comment]
ref 134005

**Comment by shashichilappagari** [comment]
@abotsiev Just checking to see if there is any update.

**Comment by abotsiev** [comment]
@shashichilappagari we checked internally with your model IR and a few driver versions. You were right and NPU driver that I've shared doesn't include the fix, since release branch was cut off a bit earlier. 

The proper fix for FP version of model would be available in the next release, expected around ww12-13 (including Linux version). Would that timeline work for you?

We also noticed that quantized version currently has some accuracy and performance issues on NPU. Is it critical for you or FP version would be sufficient for your project?

Sorry for delay in my response. I was out for a few days.

**Comment by shashichilappagari** [comment]
@abotsiev Thanks for the update. The FP model was actually working for us though we did not evaluate it on a dataset. We will do that and let you know the results. 

Regarding quant models, we are seeing a lot of interest from our customer base about quantized performance on NPU. It would be much appreciated if you can let us know the timeline roughly so that we can plan accordingly.

**Comment by abotsiev** [comment]
@shashichilappagari update from the engineering team

1. Driver release with a fix for compilation for quantized model on NPU is expected withing a few next week. It should also include Linux version. I'll keep you posted.
2. Accuracy debug is work in progress, we observed minor inaccuracy on a few layers. We'll keep working on this and hope it wouldn't impact real application accuracy visibly.
3. No update on performance issue with quantized version so far, hope to prioritize debugging during this week

**Comment by shashichilappagari** [comment]
@abotsiev any update on the drivers?

**Comment by abotsiev** [comment]
@shashichilappagari updated Linux driver is posted at https://github.com/intel/linux-npu-driver. Can you please check and let us know on results?

**Comment by shashichilappagari** [comment]
@abotsiev Thanks for the update. We will check and let you know.

**Comment by shashichilappagari** [comment]
@abotsiev we tried the latest driver (both linux and windows) and still are getting compiler errors.

here is the error message
```
RuntimeError: Exception from src\inference\src\core.cpp:102:
[ GENERAL_ERROR ] Exception from src\vpux_plugin\src\plugin.cpp:432:
LevelZeroCompilerInDriver: Failed to compile network. Error code: 2013265924.
```

Do you have any quantized model (xml and bin files) that is known to work? If so, we can try on that model.

**Comment by abotsiev** [comment]
@shashichilappagari we checked locally and you are totally right, the fix is not present in this driver release. Most likely this is due to earlier code freeze and branching policy. Anyway, I'm sorry for inconvenience again.

We are expecting updated driver release shortly and will verify the fix locally first, to let you know an actual status. Hope to get back with an update by the middle of the next week. 

Please let us know if you have any expected timeline and/or dependencies.

**Comment by darius-chirla** [comment]
Hello @shashichilappagari!
We were able to compile the network on our side on Windows with the latest NPU driver(**32.0.100.2267**) from https://www.intel.com/content/www/us/en/download/794734/intel-npu-driver-windows.html
Please let us know if the compilation problem is not reproduceable on your side as well after installing the latest driver!

**Comment by shashichilappagari** [comment]
Hi @darius-chirla Thanks for the update. The quantized model now compiles with the latest windows driver. However, the frames per second (FPS) achieved by the quant model is significantly worse compared to the float model. As a reference, we are experimenting with yolov8n model which gives 116FPS while the quant model gives around 22FPS. Could we be missing some settings? Any help would be much appreciated.

**Comment by abotsiev** [comment]
@shashichilappagari thank you for the update and confirmation. Indeed, we see the same issue with performance of quantized model, but didn't have a chance to investigate yet. That is unexpected and I don't see any simple settings that may solve it right away. We'll try to put it on priority list for the next sprint (starts next Monday) to unblock your work.

Please let us know if you have any timeline or dependencies for your project, that would help us to plan accordingly.

**Comment by abotsiev** [comment]
@shashichilappagari it's pretty hard to say in general (depends on topology). I would recommend to take a look at OpenVINO benchmark data, using setting like below (not it should cover NPU as well + comparison of different datatypes) https://docs.openvino.ai/2024/about-openvino/performance-benchmarks.html#

![image](https://github.com/openvinotoolkit/openvino/assets/70644971/66d14b34-3b6c-45a8-a84a-919db8900b36)

Got it, thank you. We started working on quantized model and got first investigation results. Our team would be on holidays 1-2 next weeks, so engineering work most likely would start around ww20. Please let us know if there would be any urgency for quantized version of that model.

**Comment by AlinaMingiuc** [comment]
Hi @shashichilappagari 
A performance improvement was done through the above mentioned PR and it will be contained in the upcoming NPU driver.

**Comment by shashichilappagari** [comment]
Hi @AlinaMingiuc Thanks for the update. We are currently using the latest NPU driver released a couple of weeks ago. We also noticed that quantized models compiled suing OpenVINO2024.0 already show improved performance. We can share our benchmark results if you are interetsed.

**Comment by ferrine** [comment]
are driver and compiler planned to be part of nixpkgs? 

https://github.com/NixOS/nixpkgs/issues/348739
