### PR TITLE
Support clang-cl build on Windows

### PR DESCRIPTION
**Pull request by yolanda15**
### Summary
Clang-cl is an optional component in Visual Studio 2026 that can be installed as a compiler option to replace default cl.exe.
To enable it, just add "-T ClangCL" when config openvino project, e.g.:
`cmake -G "Visual Studio 18 2026" -T ClangCL <path/to/openvino>`

This PR extends the CMake/toolchain to support clang-cl build on Windows.
In our experiment on NPU compilation, it helps reduce the geomean compilation time of 50 models by ~8% comparing to the default VS2026 release build.

### Details:
 •	Warning/flag handling was adjusted so clang-cl gets Clang-style options, while MSVC-only flags are kept away from incompatible tools.
 •	Windows SDL/security flag handling was refined for clang-cl/MSVC compatibility.
 •	Third-party dependency setup was adjusted to better tolerate Windows clang-cl builds and warning-as-error interactions.
 •	Intel CPU third-party build logic was updated substantially to better support clang-cl.
 •	Multiple test CMake files were adjusted so tests can build under the clang-cl configuration.
 •	win_mmap_object.cpp was updated so HANDLE validity checks are not constexpr under Clang, avoiding INVALID_HANDLE_VALUE constexpr issues.
 •	attribute_adapter.hpp was changed to disable EnumAttributeAdapterBase extern-template imports for Windows clang-cl, preventing unresolved enum-adapter symbols from dllimport.
 •	Root CMakeLists.txt added Windows Clang warning suppressions to reduce noisy compatibility diagnostics.

### Tickets:
 CVS-184750: [WebNN][NPU] Compile time needs optimization

### AI Assistance:
 - *AI assistance used: yes/no*
 Yes.
 - *If yes, summarize how AI was used and what human validation was performed (build/tests/manual checks).*
 Human runs config to enable clang-cl in build solution. AI run build, test, and fix errors and warnings. Human reviewed the change and provide feedbacks on code consistency, reducing redundant config across files and remain changes in-tree to avoid third-party dependency.

### CODE REVIEW

**Comment by p-durandin** [comment]
build_jenkins

**Comment by rkazants** [comment]
@mryzhov, @olpipi, could you please review it?

**Comment by p-durandin** [comment]
@yolanda15 please add fixes for CI issues

**Comment by yolanda15** [comment]
@p-durandin I've uploaded the new version with the fix. The CI failures were caused by one redundant line on "-Wno-suggest-override" without a guard. I have removed it in the new version. My local build with vs2026 on the test project passed now. Could you rerun the check? Thanks!

**Comment by p-durandin** [comment]
build_jenkins

**Comment by p-durandin** [comment]
@yolanda15 CPU functional test failed:
[ RUN      ] smoke_ConvertCPULayerTest_to_fp8_Dynamic/ConvertCPULayerTest.CompareWithRefs/IS=[1..5.2..22.2..9.1..4]_TS=(2.17.5.4)_(5.2.3.2)_(1.10.4.1)_inputPRC=f16_specialValue=none_targetPRC=f8e4m3__inFmts=nchw_outFmts=nchw_primitive=acl
src/plugins/intel_cpu/tests/functional/utils/cpu_test_utils.cpp:248: Failure
Value of: primTypeCheck(primType)
  Actual: false
Expected: true
primType is unexpected : unknown_f16 Expected : ref_f16

Please take a look locally

**Comment by yolanda15** [comment]
> @yolanda15 CPU functional test failed: [ RUN ] smoke_ConvertCPULayerTest_to_fp8_Dynamic/ConvertCPULayerTest.CompareWithRefs/IS=[1..5.2..22.2..9.1..4]_TS=(2.17.5.4)_(5.2.3.2)_(1.10.4.1)_inputPRC=f16_specialValue=none_targetPRC=f8e4m3__inFmts=nchw_outFmts=nchw_primitive=acl src/plugins/intel_cpu/tests/functional/utils/cpu_test_utils.cpp:248: Failure Value of: primTypeCheck(primType) Actual: false Expected: true primType is unexpected : unknown_f16 Expected : ref_f16
> 
> Please take a look locally

@p-durandin Thanks for the information! Is it possible to rerun this test only? I don't have an arm64 Linux machine to reproduce locally. I checked the generated cmake files before and after my change for the arm64 cross compile build. No obvious difference.

**Comment by p-durandin** [comment]
@yolanda15  please consider copilot remarks and update PR to master branch

**Comment by yolanda15** [comment]
Thanks! I have rebased the change and uploaded new commit that resolved the copilot remarks. @p-durandin, please take a look.

**Comment by p-durandin** [comment]
build_jenkins

**Comment by p-durandin** [comment]
LGTM.
@olpipi @openvinotoolkit/openvino-ie-cpu-maintainers  please take a look

**Comment by maxnick** [comment]
@allnes , could you please review?

File: src/plugins/intel_cpu/thirdparty/CMakeLists.txt [hunk 1]
```diff
@@ -183,10 +203,26 @@ endif()
...
     add_subdirectory(mlas EXCLUDE_FROM_ALL)
+
     # 3rd-party code (Windows): don't fail the build on its warnings, but don't hide them either
-    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR (OV_COMPILER_IS_INTEL_LLVM AND WIN32))
+    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR (OV_COMPILER_IS_INTEL_LLVM AND WIN32) OR OV_COMPILER_IS_CLANG_CL)
         target_compile_options(mlas PRIVATE $<$<COMPILE_LANGUAGE:C,CXX>:/WX->)
     endif()
+
+    if(OV_COMPILER_IS_CLANG_CL)
+        # Keep the MLAS target baseline ISA unchanged. The MLAS submodule already
```
Comment (allnes) [inline src/plugins/intel_cpu/thirdparty/CMakeLists.txt:213]: The CPU plugin still contains AVX-512 code in a static initializer outside MLAS. On an i9-14900K without AVX-512, the DLL fails to load with `0xC000001D` before ISA dispatch. Disassembly points to initialization of `ov::threading::_streams_executor_mutex` in the AVX-512 cross-compiled objects.

Please move this initialization to a baseline-compiled translation unit and check the other cross-compiled files for global initialization.

File: src/common/util/src/os/win/win_mmap_object.cpp [hunk 2]
```diff
@@ -274,13 +274,27 @@ class HandleHolder {
         return m_handle;
     }
 
+#if defined(__clang__)
```
Comment (allnes) [inline src/common/util/src/os/win/win_mmap_object.cpp:277]: This fixes the `INVALID_HANDLE_VALUE` constexpr issue here, but the full build fails on the same expression in bundled ONNX:

`thirdparty/onnx/onnx/onnx/common/scoped_resource.h:59:37: error: non-type template argument is not a constant expression`

Since ONNX is part of the default build, please fix this path as well and verify the full `ALL` build.

File: CMakeLists.txt [hunk 3]
```diff
@@ -36,6 +36,15 @@ project(OpenVINO
         HOMEPAGE_URL "https://docs.openvino.ai/2026/index.html"
         LANGUAGES C CXX)
 
+# Reduce noisy, non-actionable Clang compatibility warnings globally.
+# Keep this narrowly focused on compiler-compatibility warnings so that
+# actionable diagnostics (linker warnings, buffer/UB warnings, logic issues)
+# remain visible. Adjust flags if you want to add/remove suppressed classes.
+if(WIN32 AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
+    message(STATUS "Applying global clang-cl (Windows) warning suppressions to reduce noise (C++ only)")
+    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-c++98-compat -Wno-pre-c++14-compat -Wno-pre-c++17-compat -Wno-unknown-warning-option")
```
Comment (allnes) [inline CMakeLists.txt:45]: The full clang-cl build still fails in IPF because `/WX` turns `-Wsuggest-override` and `-Wsign-compare` diagnostics into errors. GPU oneDNN also receives the unsupported `-fstack-protector-all` option. These global suppressions do not address either problem.

Please handle the flags on the affected targets and verify the full build.

File: cmake/developer_package/compile_flags/functions.cmake [hunk 4]
```diff
@@ -338,8 +353,25 @@ endfunction()
 #
 macro(ov_add_compiler_flags)
     foreach(flag ${ARGN})
-        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${flag}")
-        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${flag}")
+        if(OV_COMPILER_IS_CLANG_CL)
```
Comment (allnes) [inline cmake/developer_package/compile_flags/functions.cmake:356]: With `CMAKE_COMPILE_WARNING_AS_ERROR=ON`, the CPU plugin build fails at `win_system_conf.cpp:91` because `cur_numa_mask` is set but not used. Please fix this warning and verify the clang-cl build with Werror enabled.

File: src/plugins/intel_cpu/thirdparty/CMakeLists.txt [hunk 5]
```diff
@@ -148,10 +148,30 @@ function(ov_add_onednn)
...
+    # oneDNN treats clang-cl as Clang in its MSVC generator path and adds
+    # Unix-style frame-pointer flags (-fno-omit-frame-pointer and
+    # -mno-omit-leaf-frame-pointer). clang-cl ignores these flags and reports
+    # noisy -Wunknown-argument warnings, while oneDNN's MSVC branch avoids them.
+    # Temporarily expose clang-cl as MSVC only while configuring oneDNN, then
+    # restore the real compiler IDs immediately after add_subdirectory.
+    if(OV_COMPILER_IS_CLANG_CL)
+        set(OV_ONEDNN_C_COMPILER_ID ${CMAKE_C_COMPILER_ID})
+        set(OV_ONEDNN_CXX_COMPILER_ID ${CMAKE_CXX_COMPILER_ID})
+        set(CMAKE_C_COMPILER_ID MSVC)
```
Comment (allnes) [inline src/plugins/intel_cpu/thirdparty/CMakeLists.txt]: Overwriting `CMAKE_<LANG>_COMPILER_ID` can make dependency checks cache MSVC-specific decisions while the actual compiler is Clang. Restoring the value after `add_subdirectory` does not undo those decisions.

Please use the compiler frontend variant or adjust the incompatible oneDNN flags directly.

**Review by allnes — CHANGES_REQUESTED** [review]

File: cmake/developer_package/target_flags.cmake [hunk 6]
```diff
@@ -109,6 +109,9 @@ if(CMAKE_CXX_COMPILER_ID MATCHES "^(Apple)?Clang$")
     if(CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
         set(OV_COMPILER_IS_APPLECLANG ON)
     endif()
+    if(WIN32 AND MSVC AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
+        set(OV_COMPILER_IS_CLANG_CL ON)
```
Comment (allnes) [inline cmake/developer_package/target_flags.cmake:113]: Could this be validated with an official standalone LLVM Windows release and the exact version documented? The `clang-cl.exe` bundled with Visual Studio is an unmodified upstream LLVM binary, but the toolchain selected by `-T ClangCL` is still tied to the LLVM version shipped with that Visual Studio update and uses the Microsoft STL/runtime and MSBuild integration. Using a pinned official LLVM release through `LLVMInstallDir` would make the compiler version explicit and reproducible instead of changing with Visual Studio updates.

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (yolanda15) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: I cannot reproduce it when build the onnx project. It seems the `constexpr` is already removed in the latest openvino version?
https://github.com/onnx/onnx/blob/2bb50465112feca9003e1ed654d77f01ff1415ca/onnx/common/scoped_resource.h#L59

File: cmake/developer_package/compile_flags/functions.cmake (hunk 4 above)
Comment (yolanda15) [reply cmake/developer_package/compile_flags/functions.cmake:356]: I tried to CMAKE_COMPILE_WARNING_AS_ERROR=ON, besides this unused variable, there are also many unused functions. Do you think it's better to keep the warning as it is or suppress it for clang-cl?

File: cmake/developer_package/target_flags.cmake (hunk 6 above)
Comment (yolanda15) [reply cmake/developer_package/target_flags.cmake:113]: The intention of this PR is to reduce compile time for NPU pipeline. I expect the clang-cl build is most likely used for an official release?
The standalone LLVM Windows release requires different config than the ClangCL toolchain setting, even though most flag compatibility issues can be addressed similarly. If needed, we may enable it in a separate PR?

File: CMakeLists.txt (hunk 3 above)
Comment (yolanda15) [reply CMakeLists.txt:45]: Could you share how to config for IPF? I checked my current build has below set:
```
ENABLE_AUTO=ON
ENABLE_IPF_CLIENT_API=ON
```
But cannot reproduce the error or warnings for `-Wsuggest-override` and `-Wsign-compare` diagnostics.
I have fixed the unsupported `-fstack-protector-all` option in the new commit.

**Comment by yolanda15** [comment]
@allnes Thanks for the comments! I have resolved some of them in the new commit. Others may need further clarification. Please take a look. Thanks!

**Comment by allnes** [comment]
build_jenkins

**Comment by p-durandin** [comment]
@yolanda15 please fix CI errors

**Comment by yolanda15** [comment]
@p-durandin @allnes I have fixed the clang-tidy build error which is caused by the non-const global introduced to avoid the instantiating error in the AVX-512 cross-compiled object. Other failures are downloading issues, seems unrelated.
I also enhanced previous fix to clear up more warnings as errors. Please take a look. Thanks!

**Comment by p-durandin** [comment]
build_jenkins

**Comment by yolanda15** [comment]
> build_jenkins

There are new ci failures caused by latest commit: unused variable "host_alloc" was not removed and redefined on Ubuntu by mistake. I tried to verify it on Ubuntu but was not updated with latest commit that missed this failure. Sorry for the inconvenience! Could you reun the ci test? Thanks @p-durandin

**Comment by p-durandin** [comment]
build_jenkins

**Comment by yolanda15** [comment]
> build_jenkins

Thanks Pavel!
@allnes, all checks have passed now after new fix. Could you take a look if any more comments? Thanks!

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (yolanda15) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: Sorry, I found I had a local fix in onnx that missed this error. I will take a look if this has to be fixed from onnx only.

File: CMakeLists.txt (hunk 3 above)
Comment (allnes) [reply CMakeLists.txt:45]: Re-tested the current head `ffd27ead` with a clean Release build using VS 2026 and clang-cl 20.1.8. The default build still fails in `ClientApi.vcxproj`: the first error is `ClientApiProxy.h(43,14): GetProperties overrides a member function but is not marked override [-Werror,-Wsuggest-override]`, and `ClientApiCJson.cpp:411` also fails with `[-Werror,-Wsign-compare]`.

The GPU oneDNN stack-protector issue mentioned earlier is fixed now: its ExternalProject patch ran before the build and replaced the flag in 17 generated projects. IPF remains a blocker for the advertised default clang-cl build. Please fix or update the dependency and add a clean default `-T ClangCL` CI job.

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (allnes) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: Re-tested the current head `ffd27ead`; the default build still fails at this exact bundled ONNX path:

`thirdparty/onnx/onnx/onnx/common/scoped_resource.h(59,37): error: non-type template argument is not a constant expression`

The `INVALID_HANDLE_VALUE` integer-to-pointer cast cannot be used as this pointer NTTP under clang-cl. Please include the missing ONNX fix (runtime sentinel or Windows specialization) or update the submodule before merging; otherwise the default build cannot complete.

File: src/plugins/intel_cpu/thirdparty/CMakeLists.txt [hunk 7]
```diff
@@ -150,8 +150,28 @@ function(ov_add_onednn)
 
     add_subdirectory(onednn EXCLUDE_FROM_ALL)
 
+    if(WIN32
+       AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang"
+       AND (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC"
+            OR OV_COMPILER_IS_CLANG_CL))
+        add_custom_target(onednn_patch_clang_cl_frame_pointer_flags
```
Comment (allnes) [inline src/plugins/intel_cpu/thirdparty/CMakeLists.txt:157]: This build-time rewrite is too late for the Visual Studio generator. In a clean VS 2026 / clang-cl 20.1.8 build, this target reported replacing the frame-pointer flags in four generated projects, but MSBuild had already evaluated those `.vcxproj` files. The same invocation emitted 365 `unknown argument ignored: -fno-omit-frame-pointer` warnings from the oneDNN CPU targets; the files contained `/Oy-` only after the build, so the first and subsequent builds use different options.

Please set the frame-pointer option before project generation (or patch oneDNN target/source options) instead of modifying an already loaded build graph.

File: src/cmake/openvino.cmake [hunk 8]
```diff
@@ -58,6 +58,14 @@ target_link_libraries(${TARGET_NAME}
     PUBLIC $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.1>>:stdc++fs>
     $<$<AND:$<CXX_COMPILER_ID:Clang>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0>>:c++fs>)
 
+if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" OR OV_COMPILER_IS_CLANG_CL)
+    # openvino links object files from openvino_core_obj together with static
+    # libraries that include openvino_core headers with dllimport attributes.
+    # MSVC link.exe and clang-cl's lld-link can warn about these known local
+    # imports while producing the final runtime DLL.
+    target_link_options(${TARGET_NAME} PRIVATE "/IGNORE:4217,4286")
```
Comment (allnes) [inline src/cmake/openvino.cmake:66]: This condition also changes the diagnostic behavior of the regular MSVC build, although the PR is adding clang-cl support. LNK4217 and LNK4286 are DLL import/export diagnostics that can expose real linkage or ABI mistakes, so suppressing them for the entire OpenVINO target can hide unrelated regressions.

Please scope this to `OV_COMPILER_IS_CLANG_CL` and, if possible, to the specific affected object libraries. If standard MSVC also needs the suppression, that should be justified and covered separately.

**Comment by p-durandin** [comment]
build_jenkins

File: src/cmake/openvino.cmake (hunk 8 above)
Comment (yolanda15) [reply src/cmake/openvino.cmake:66]: Fixed in the updated commit. The MSVC has similar target_link_options but only limited to the core module.

File: src/plugins/intel_cpu/thirdparty/CMakeLists.txt (hunk 7 above)
Comment (yolanda15) [reply src/plugins/intel_cpu/thirdparty/CMakeLists.txt]: Done. Found a better solution on this to use oneDNN's helper variable CMAKE_BASE_NAME to pass the compiler driver base name.

File: cmake/developer_package/compile_flags/functions.cmake (hunk 4 above)
Comment (yolanda15) [reply cmake/developer_package/compile_flags/functions.cmake:356]: The unused function errors are all gone after rebase. Resolved more unused variables and private field errors for a clean clang-cl build with CMAKE_COMPILER_WARNING_AS_ERROR=ON in the updated commit.

File: CMakeLists.txt (hunk 3 above)
Comment (yolanda15) [reply CMakeLists.txt:53]: Sorry for missing the IPF submodule in previous build. I have reproduced the error and fixed it in the updated commit.
Regarding the  `-T ClangCL` CI job, I checked the ` .github/workflows`, seems only ninja build is supported on Windows build. Is it correct? Do I need to create a ninja build job instead?

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (yolanda15) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: Fixed the error with a ONNX patch in the updated commit.

**Comment by p-durandin** [comment]
build_jenkins

**Comment by yolanda15** [comment]
> build_jenkins

@p-durandin  The new clang-cl job failed to run on the github hosted `windows-2022` due to missing vs2026. I'm now switching to a different runner: `windows-2025` in the updated commit. Could you have a check? Thanks!

**Comment by yolanda15** [comment]
> > build_jenkins
> 
> @p-durandin The new clang-cl job failed to run on the github hosted windows-2022 due to missing vs2026. I'm now switching to the self-hosted runner: aks-win-16-cores-32gb-vs2026-build in the updated commit. Could you have a check? Thanks!

@p-durandin, please ignore my previous comment. Let me try another approach with the github hosted windows-2025-vs2026 runner which equipped with with both VS2026 and clang-cl.

**Comment by allnes** [comment]
build_jenkins

**Comment by yolanda15** [comment]
> build_jenkins

The previous commit verified the availability of VS2026 and clang-cl on runner `windows-2025`. It failed due to Arm64 toolchain was selected. I have updated the workflow to skip the check and run cmake directly. Please verify again, Thanks!  @p-durandin  @allnes

File: src/inference/src/dev/threading/istreams_executor.cpp [hunk 9]
```diff
@@ -20,6 +20,9 @@
 namespace ov {
 namespace threading {
 
+// Baseline definition for the shared streams executor mutex.
+std::mutex _streams_executor_mutex;
```
Comment (praasz) [inline src/inference/src/dev/threading/istreams_executor.cpp]: This change should not be required as right it works without it.

**Comment by p-durandin** [comment]
build_jenkins

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (praasz) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: The code changes should not be required in general.
It has to be explained why it reject

File: src/common/snippets/src/pass/positioned_pass.cpp [hunk 10]
```diff
@@ -16,6 +16,10 @@ PassPosition::PassPosition(Place pass_place) : m_place(pass_place) {
     OPENVINO_ASSERT(utils::any_of(m_place, Place::PipelineStart, Place::PipelineEnd),
                     "Invalid arg: pass_type_info and pass_instance args could be omitted only for "
                     "Place::PipelineStart/Place::PipelineEnd");
+    // m_pass_instance is otherwise only read from the header-defined template path,
+    // which can trigger clang's unused-private-field warning in TUs that do not
+    // instantiate that template.
+    static_cast<void>(m_pass_instance);
```
Comment (praasz) [inline src/common/snippets/src/pass/positioned_pass.cpp:22]: This should be not required the compiler should be set to be aligned with others regular gcc, clang not complain about in this module

**Comment by yolanda15** [comment]
> build_jenkins

Thanks! The windows clang-cl job seems work. Fixed the missing onnx patch file in the updated commit and also refactored the previous stream mutex change to avoid any consistency risk. 
@p-durandin, please check again, Thanks!

File: src/inference/src/dev/threading/istreams_executor.cpp (hunk 9 above)
Comment (yolanda15) [reply src/inference/src/dev/threading/istreams_executor.cpp]: Yes, this is removed in latest commit.

File: src/common/snippets/src/pass/positioned_pass.cpp (hunk 10 above)
Comment (yolanda15) [reply src/common/snippets/src/pass/positioned_pass.cpp:22]: Thanks for the comment!
I checked the exact compile lines for positioned_pass.cpp on both platforms. Neither the Linux clang++ build nor the Windows clang-cl build explicitly enables `-Wunused-private-field`.
On Linux, this TU is compiled with the regular clang++ driver using `-Wall, -Wmissing-declarations`, and `-Wsuggest-override`, and that warning is not emitted for this module. On Windows, the same TU is compiled with clang-cl in MSVC-driver mode (`--target=amd64-pc-windows-msvc, /W3, /WX`), and the warning is emitted there even without an explicit `-Wunused-private-field` flag.
`m_pass_instance` is only read through a header-defined template path, so TUs that do not instantiate that path can still be diagnosed as having an unused private field in clang-cl mode. 
Based on that, I narrowed the workaround to clang-cl only, so the source change is limited to the configuration that actually reports the warning. Does that make sense?

Comment (yolanda15) [reply src/common/snippets/src/pass/positioned_pass.cpp:22]: Regarding the change for "win_mmap_object.cpp", this is windows only code, so the error is only reported for clang-cl. To make this clear, I have strengthened the existing comments for better explanation. Please take a look at the updated commit. Thanks!
The change is required specifically because `INVALID_HANDLE_VALUE` expands to `((HANDLE)(LONG_PTR)-1)`. The existing alias passes that pointer value as a non-type template argument: `ScopedResource<INVALID_HANDLE_VALUE, close_handle>`. Such an integer-to-pointer conversion is not a valid constant expression for a pointer non-type template argument in standard C++. clang-cl therefore rejects the alias, while MSVC accepts it as an extension. Linux Clang does not encounter it because the code is guarded by _WIN32.

**Comment by yolanda15** [comment]
Fixed the missing leading space in the empty line of the generated patch file. Please verify on the window clang-cl ci test. Thanks! @praasz @p-durandin

**Comment by p-durandin** [comment]
build_jenkins

**Review by olpipi — COMMENTED** [review]
OpenVINO ships prebuilt Windows binaries, so a pretty common scenario is OpenVINO built with clang-cl but the consuming app built with a MSVC. 
clang-cl aims for MSVC ABI compatibility, so this should just work, but has that actually been tested? For example: building OV with clang-cl and linking a MSVC-built sample app against it.
It would be good to have a CI job for that

**Comment by yolanda15** [comment]
> OpenVINO ships prebuilt Windows binaries, so a pretty common scenario is OpenVINO built with clang-cl but the consuming app built with a MSVC. clang-cl aims for MSVC ABI compatibility, so this should just work, but has that actually been tested? For example: building OV with clang-cl and linking a MSVC-built sample app against it. It would be good to have a CI job for that

Yes, I have verified it works with a sample project built by MSVC. The new clang-cl CI job is also updated to include this ABI check. Please verify. Thanks!

File: src/common/util/src/os/win/win_mmap_object.cpp (hunk 2 above)
Comment (yolanda15) [reply src/common/util/src/os/win/win_mmap_object.cpp:277]: The change is required specifically because INVALID_HANDLE_VALUE expands to ((HANDLE)(LONG_PTR)-1). The existing alias passes that pointer value as a non-type template argument: ScopedResource<INVALID_HANDLE_VALUE, close_handle>. Such an integer-to-pointer conversion is not a valid constant expression for a pointer non-type template argument in standard C++. clang-cl therefore rejects the alias, while MSVC accepts it as an extension. Linux Clang does not encounter it because the code is guarded by _WIN32.
To make this clear, I have strengthened the existing comments for better explanation.

File: CMakeLists.txt (hunk 3 above)
Comment (yolanda15) [reply CMakeLists.txt:53]: Created a new CI job to test  `-T ClangCL` successfully. Resolving this comment.

**Comment by p-durandin** [comment]
build_jenkins

**Comment by yolanda15** [comment]
> build_jenkins

Got a failure due to "cmd /c" is not recognized in github action when calling the openvino setup script. Fixed it by an explicit "shell: cmd" step in the updated commit. Please have a check, Thanks! @p-durandin

**Comment by p-durandin** [comment]
build_jenkins

File: src/core/include/openvino/core/attribute_adapter.hpp [hunk 11]
```diff
@@ -253,6 +253,10 @@ namespace element {
 enum class Type_t;
 }
 
+// clang-cl on Windows may dllimport EnumAttributeAdapterBase members from the core DLL
+// even though these methods are defined inline in the header, which leads to unresolved
+// enum-adapter symbols in consumers. Let clang-cl instantiate them locally instead.
+#if !(defined(_WIN32) && defined(__clang__))
```
Comment (praasz) [inline src/core/include/openvino/core/attribute_adapter.hpp]: That was intentional to avoid local instances
