### ISSUE TITLE
[Bug] Unable to build openvino for ubuntu 18.04, throws no match for ‘operator[]’ 

### ISSUE THREAD

**Issue by anjalirai-intel** [openvinotoolkit/openvino#11973]
- OpenVINO=> 2021.4.752
- Operating System / Platform => Linux Ubuntu 18.04
- Compiler => :grey_question:
- Problem classification => :grey_question:

##### Detailed description
Previously Openvino used to work with Ubuntu 18.04, but very recently, It has stopped working, 
I was trying to build openvino for our application but it started failing with some reason. These are the errors which we didn't see earlier.

While performing make, initially it throwed error **"Protobuf compiler not found"**, so i went ahead and installed apt-get install protobuf-compiler

Then again it started error **Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)**, now this time i installed  apt-get install -y  libprotobuf-dev

And then now it is throwing error 
```
[ 43%] Building CXX object CMakeFiles/onnx.dir/onnx/shape_inference/implementation.cc.o
    /tmp/pip-install-178o727p/onnx_6c6138ba506e4fd0b670c5471525c410/onnx/defs/sequence/defs.cc: In function ‘bool onnx::BuildSequenceMapBodyFunc(const onnx::FunctionBodyBuildContext&, const onnx::OpSchema&, onnx::FunctionProto&)’:
    /tmp/pip-install-178o727p/onnx_6c6138ba506e4fd0b670c5471525c410/onnx/defs/sequence/defs.cc:675:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
             seq_at_node.add_output(g_inputs[inputIndex].name());
                                            ^
    /tmp/pip-install-178o727p/onnx_6c6138ba506e4fd0b670c5471525c410/onnx/defs/sequence/defs.cc:683:37: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
             identity.add_output(g_inputs[inputIndex].name());
                                         ^
    /tmp/pip-install-178o727p/onnx_6c6138ba506e4fd0b670c5471525c410/onnx/defs/sequence/defs.cc:741:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
         int64_t dtype = g_outputs[outputIndex].type().tensor_type().elem_type();
                                  ^
    [ 45%] Building CXX object CMakeFiles/onnx.dir/onnx/version_converter/convert.cc.o
    CMakeFiles/onnx.dir/build.make:830: recipe for target 'CMakeFiles/onnx.dir/onnx/defs/sequence/defs.cc.o' failed
```

##### Steps to reproduce
1. git clone https://github.com/gramineproject/examples/tree/master/openvino
2. cd examples/openvino
3. wget https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4.2/l_openvino_toolkit_dev_ubuntu18_p_2021.4.752.tgz
        tar xzf l_openvino_toolkit_dev_ubuntu18_p_2021.4.752.tgz
4. source l_openvino_toolkit_dev_ubuntu18_p_2021.4.752/bin/setupvars.sh
5. make

[openvino_make_errors.log](https://github.com/openvinotoolkit/openvino/files/8989440/openvino_make_errors.log)
##### Issue submission checklist

 - [ Y] I report the issue, it's not a question
   
 - [ Y] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
   
 - [Y ] There is reproducer code and related data files: images, videos, models, etc.

**Comment by Iffa-Meah** [comment]
@anjalirai-intel 
1. Did you try to update before installing that? (sudo apt-get update)
2. OpenVINO version 2021.4 is not the latest version. Are there any reasons that would restrict you from upgrading to the latest version? (2022.1)

**Comment by anjalirai-intel** [comment]
@Iffa-Meah Yes, i have done apt update. Yes, right now we won't be able to upgrade it to 2022. But my biggest concern is openvino 2021 was working till last week and now suddenly we are facing setup issues.

**Comment by brmarkus** [comment]
Can you try to isolate your build environment into e.g. a Docker container or Python virtual-environment with specific, frozen versions of your example's dependencies (like using a "requirements.txt")? It looks like dependencies like ONNX or ProtoBuf have updated recently and braking your local build.

**Comment by anjalirai-intel** [comment]
It is isolated. All these failures are within docker container

**Comment by brmarkus** [comment]
Ok... but in your Dockerfile you might call "sudo apt-get update", which will result in just the currently latest versions, which might change every minute. You might need to pin and freeze your dependencies to specific versions or keep them below a certain version.

**Comment by anjalirai-intel** [comment]
But, this requirements.txt we need from openvino and i feel all the package details should be correctly mapped in openvino/install_dependencies/install_openvino_dependencies.sh

Having a list of packages to be installed automatically for the workload setup, in which setup is throwing error.

**Comment by brmarkus** [comment]
From your description it looked like you started to manually install missing components like `apt-get install protobuf-compiler` and `apt-get install -y libprotobuf-dev`.

Are you sure these dependencies are needed by OpenVINO itself of by your examples from `git clone https://github.com/gramineproject/examples/tree/master/openvino`?
As you just clone HEAD/LATEST revision - has the code changed since you built it successfully the last time?
(without tricks and without doing a clean docker-build the command "docker build" might not clone again, but might use an older local intermediate build layer)

**Comment by anjalirai-intel** [comment]
I had to do manually because openvino failed in docker with error Protobuf compiler not found. To debug the issue further. I manually created the docker container and started debugging and that's why i installed those libraries. 

Yes, These dependencies are needed by Openvino itself because i was still doing workload setup. If you want to verify it just go ahead and install onnx on Ubuntu 18.04 using python

The code has not changed. We can reproduce it without our application as well. Just install onnx using python

**Comment by brmarkus** [comment]
Installing OpenVINO requires to install dependencies via `sudo -E /opt/intel/openvino_2021/install_dependencies/install_openvino_dependencies.sh`, see "https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html#step-2-install-external-software-dependencies".

Installing Model-Optimizer installs dependencies as well - like TensorFlow, like ONNX, see "https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html#step-4-configure-the-model-optimizer", where you either install all supported framework's dependencies (`sudo /opt/intel/openvino_2021/deployment_tools/model_optimizer/install_prerequisites/install_prerequisites.sh`) or can choose to e.g. only install the ones for Model-Optimizer and ONNX via e.g. `install_prerequisites_onnx.sh`.

The samples and demos can be compiled like this successfully; the provided installation scripts take care about which dependency in which version and package to install.

**Comment by anjalirai-intel** [comment]
@brmarkus I am facing issue in `/opt/intel/openvino_2021/install_dependencies/install_openvino_dependencies.sh`. 

When the openvino is trying to install onnx, it fails there because protobuf and protobuf-compiler is dependency of latest onnx

**Comment by brmarkus** [comment]
Can you uninstall your previously, manually installed components mentioned above (including to remove them from APT-cache and/or PIP-cache) first and try again?

**Comment by anjalirai-intel** [comment]
I did, that but with latest onnx version for ubuntu 18.04 bionic is not working. Do you know which onnx version is compatible for openvino 2021

**Comment by brmarkus** [comment]
You can have a look here, `/opt/intel/openvino_2021.4.752/deployment_tools/model_optimizer/requirements_onnx.txt`.
For my installed version 2021.4.752 (which is 2021.4.2) I can see this:

```
  onnx>=1.8.1
  networkx~=2.5
  numpy>=1.16.6,<1.20
  defusedxml>=0.7.1
  requests>=2.25.1

```
In my Ubuntu 18.04 environment I got this ONNX installed:

```
  $> pip list | grep -i onnx
    onnx                    1.10.2
```

**Comment by anjalirai-intel** [comment]
So, with this  onnx>=1.8.1 and with latest it is 1.12 and we have all this issue. I will try to stick with onnx version 1.8.1 for openvino 2021

**Comment by anjalirai-intel** [comment]
I tried installing onnx with specific version and got this error

Collecting protobuf (from onnx==1.10.2)
  Downloading https://files.pythonhosted.org/packages/6c/be/4e32d02bf08b8f76bf6e59f2a531690c1e4264530404501f3489ca975d9a/protobuf-4.21.0-py2.py3-none-any.whl (164kB)
[91mprotobuf requires Python '>=3.7' but the running Python is 3.6.9

**Comment by brmarkus** [comment]
Would it be possible to upgrade your Docker container from 18.04 to 20.04 (`FROM ubuntu:20.04`)? That would bring a newer Python and other newer package versions.

**Comment by anjalirai-intel** [comment]
We have to test it with both 18.04 and 20.04. It's just a week ago 18.04 was also working for openvino. I want to go to that state

**Comment by brmarkus** [comment]
By any chance would you still have local container/images of that state, or pushed the container/image to a Docker hub (internal or public) - and then export the used version of that working state (calling `pip freeze > requirements.txt`)?

You might need to roll-back protobuf as well.

**Comment by anjalirai-intel** [comment]
No, i don't have that container/images of that state now

**Comment by anjalirai-intel** [comment]
I have tried with packages when openvino was working and eventually i end up with pybind11 error. I tried installing pybind11, pybind11[global] as well using python, but it does not helps. 

Can you give me a list of exact working set of libraries which works for openvino 2021.4.752 in ubuntu 18.04 for a fresh environment

```
CMake Warning at CMakeLists.txt:451 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.

      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:

        pybind11Config.cmake
        pybind11-config.cmake
```

**Comment by brmarkus** [comment]
When setting-up a new system (like RVPs or CRBs) using Ubuntu18 and Ubuntu20 then I only use OpenVINO's install scripts.

When cloning OpenVINO source-code repo for a specific version then don't forget to specify the corresponding versions of the sub-modules as well (otherwise you clone OpenVINO, switch to a specific version but the sub-modules might still be HEAD/MASTER); don't just do a `git submodule update --init --recursive`.

I don't know and have not used your referenced repo "https://github.com/gramineproject/examples/tree/master/openvino"...

Can you confirm you can build OpenVINO from e.g. "https://github.com/openvinotoolkit/openvino/tree/releases/2021/4"?

**Comment by anjalirai-intel** [comment]
I am not building from sources. I am building from here

**Comment by anjalirai-intel** [comment]
Sorry, i closed the issue by mistake

**Comment by brmarkus** [comment]
Hmm, now I lost the overview.
You are within a Docker container, "isolated environment"? Is this an OpenVINO-container, or based on an OpenVINO docker container?
Within the container have you "fully installed" OpenVINO (by installing it, by calling the install-scripts)? Can you build the OpenVINO samples as well as the contained Open-Model-Zoo demos successfully? Can you successfully use some of the samples and demos like "hello_query_device" or "benchmark_app"?
This is just to confirm your OpenVINO installation "as-such".

Then "the real work" might just start to check your application's dependencies (CMake-dependencies, Python dependencies, thirdparty dependencies).

**Comment by anjalirai-intel** [comment]
@brmarkus I am within a docker container. No, its not an openvino container.

My whole problem is I am not able to install openvino. 

If you have something where you are able to run openvino 2021.4.752 in a fresh ubuntu 18.04 environment. I would like to know the steps

https://storage.openvinotoolkit.org/repositories/openvino/packages/2021.4.2/

**Comment by brmarkus** [comment]
Start here to download OpenVINO: https://www.intel.com/content/www/us/en/developer/tools/openvino-toolkit/download.html

And then you can "blindly" follow the installation description under "https://docs.openvino.ai/2021.4/openvino_docs_install_guides_installing_openvino_linux.html":

install it
install dependencies
source the environment (i.e. ENV variables)
model-optimizer required dependencies
install NEO-OpenCL for using the GPU

To check and run some of the demos&samples, look into "https://docs.openvino.ai/2021.4/openvino_docs_get_started_get_started_scripts.html".

**Comment by brmarkus** [comment]
Here, "https://github.com/openvinotoolkit/docker_ci", you can see how different variants of OpenVINO gets put the publicly available Docker containers.

**Comment by anjalirai-intel** [comment]
I initially tried from there, there were some issue and then someone from openvino team gave me this link to refer from

**Comment by anjalirai-intel** [comment]
Thanks for all the help. 

I am able to build openvino now by restricting onnx==1.8.1 in ./deployment_tools/model_optimizer/requirements.txt.

If i try to install separately using apt, it ends up with pybind11 error, but this way it works.

**Comment by terablade2001** [comment]
Hello.
I'm facing a similar (if not the same) problem when I'm trying to install via PIP install according to the instructions.
More specifically in a clean Ubuntu 18.04.6 LTS installation I do:
```
sudo apt update
sudo apt install -y openssh-server 
sudo apt install -y net-tools git git-gui gcc cmake vim p7zip-full p7zip-rar terminator python3-venv pkg-config cifs-utils
sudo apt install -y python3-distutils python3-dev python3-pip
sudo apt install -y libprotobuf-dev protobuf-compiler 

python3 -m venv openvino_env 
source ~/openvino_env/bin/activate
pip install --upgrade pip
pip install openvino-dev[caffe,ONNX]==2022.1.0 
```
The error I get is:
```
    [ 83%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor/utils.cc.o
    [ 84%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_proto_util.cc.o
    [ 85%] Building CXX object CMakeFiles/onnx.dir/onnx/defs/tensor_util.cc.o
    /tmp/pip-install-uhmsjdeh/onnx_624eede8790147388be0905a2c3d95b4/onnx/defs/sequence/defs.cc: In function ‘bool onnx::BuildSequenceMapBodyFunc(const onnx::FunctionBodyBuildContext&, const onnx::OpSchema&, onnx::FunctionProto&)’:
    /tmp/pip-install-uhmsjdeh/onnx_624eede8790147388be0905a2c3d95b4/onnx/defs/sequence/defs.cc:675:40: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
             seq_at_node.add_output(g_inputs[inputIndex].name());
                                            ^
    /tmp/pip-install-uhmsjdeh/onnx_624eede8790147388be0905a2c3d95b4/onnx/defs/sequence/defs.cc:683:37: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
             identity.add_output(g_inputs[inputIndex].name());
                                         ^
    /tmp/pip-install-uhmsjdeh/onnx_624eede8790147388be0905a2c3d95b4/onnx/defs/sequence/defs.cc:741:30: error: no match for ‘operator[]’ (operand types are ‘google::protobuf::RepeatedPtrField<onnx::ValueInfoProto>’ and ‘int’)
         int64_t dtype = g_outputs[outputIndex].type().tensor_type().elem_type();
```

**In this case where can I set the ONNX to 1.8.1?**
I've found the following paths inside the venv folder where I can change the `onnx>=1.8.1` to `onnx==1.8.1`, but they does not seem to affect the used onnx version:
```
vim ./lib/python3.6/site-packages/openvino/tools/mo/requirements.txt
vim ./lib/python3.6/site-packages/openvino/tools/mo/requirements_onnx.txt
```
Even if I set both in there `onnx==1.8.1` during installation it shows:
```
Collecting onnx>=1.8.1
  Using cached onnx-1.13.0.tar.gz (10.4 MB)
```
Paths where the onnx>=1.8.1 are:

Is there any other solution on this?
Thanks

**Comment by tomdol** [comment]
Looks like there's an issue in the ONNX library when combined with protobuf 3.0 https://github.com/onnx/onnx/pull/4354. Can you please manually upgrade protobuf to a newer version? According to the comments in that PR the minimum required protobuf version by ONNX is 3.12
You might need to add a special repository when doing that with APT, compile protobuf yourself but you can also try installing it with pip.

**Comment by terablade2001** [comment]
Thanks tomdol.
Your comment led me to the solution.

I had to manually clone/build/install protobuf 3.12.4 (no need to try change to onnx 1.8.1.). Thus, instead of using the default libraries `sudo apt install -y libprotobuf-dev protobuf-compiler` I used these commands (https://gist.github.com/diegopacheco/cd795d36e6ebcd2537cd18174865887b) to build protobuf at the 3.12.4 tag/version.
Then the command:
```
pip install openvino-dev[caffe,ONNX]==2022.1.0
```
completed with result: `Successfully installed fastjsonschema-2.15.3 onnx-1.12.0`. 👍
