### ISSUE TITLE
Can't read openvino pre-trained model in opencv.

### ISSUE THREAD

**Issue by chinmaydas96** [openvinotoolkit/openvino#457]
I was running the following line in raspberr pi:

`import cv2     `                                                                                                                                      

`cv2.dnn.readNet('person-detection-retail-0002/person-detection-retail-0002.xml',  `
` 'person-detection-retail-0002/person-detection-retail-0002.bin')   `

the error is following : 

** 
terminate called after throwing an instance of 'InferenceEngine::details::InferenceEngineException'
  what():  Check 'axis < static_cast<size_t>(input_rank)' failed at /teamcity/work/scoring_engine_build/releases_2020_1/ngraph/src/ngraph/op/gather.cpp:140:
While validating node 'Gather[Gather_928](patternLabel_924: float{10,20,30}, patternLabel_925: int64_t{5}, patternLabel_927: int64_t{1}) -> (??)':
The axis must => 0 and <= input_rank (axis: 4294967295).

Aborted
**

I have already build the opencv with openvino.
`import cv2 as cv                                                                                              `                                       

In [2]: print(cv.__file__)                                                                                                                                   
/home/pi/openvino/python/python3/cv2.abi3.so`

**Comment by dkurt** [comment]
That's right. This is nGraph issue fixed by https://github.com/NervanaSystems/ngraph/pull/4329 if I'm not mistaken

**Comment by dkurt** [comment]
@chinmaydas96, Can you please try the latest 2020.2 release?

**Comment by fischermario** [comment]
I got the same error message as @chinmaydas96 while trying to run the face detection test as advised by the OpenVINO Raspbian guide ([https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html#run-inference-opencv](https://docs.openvinotoolkit.org/latest/_docs_install_guides_installing_openvino_raspbian.html#run-inference-opencv)).

With the new 2020.2 release I ran the test again and got this error message instead:
```
Traceback (most recent call last):
  File "openvino_fd_myriad.py", line 12, in <module>
    _, confidences, boxes = net.detect(frame, confThreshold=0.5)
cv2.error: OpenCV(4.3.0) /home/nvidia/Downloads/opencv-4.3.0/opencv/modules/dnn/src/ie_ngraph.cpp:600: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call in function 'initPlugin'
```
This points to the same problem as before while the error description is much better this time.

Btw. I have used this model for testing with 2020.2:
[https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/face-detection-adas-0001/FP16/face-detection-adas-0001.xml](https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/face-detection-adas-0001/FP16/face-detection-adas-0001.xml)
[https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/face-detection-adas-0001/FP16/face-detection-adas-0001.bin](https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/1/face-detection-adas-0001/FP16/face-detection-adas-0001.bin)

(Out of curiosity: What is the difference between the models in the three directories "1", "2", "3" inside [https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/](https://download.01.org/opencv/2020/openvinotoolkit/2020.2/open_model_zoo/models_bin/)?)

@dkurt: If this behavior was really fixed by the mentioned pull request (which was merged into master on February 13th) then reading the new model format should work with OpenVINO 2020.2 because it relies on a ngraph version (edc65ca0111f86a7e63a98f62cb17d153cc2535c) from March 31st.

**Comment by alalek** [comment]
@fischermario Mentioned problem with "deprecated format" in VPU plugin should be workarounded in OpenCV here: https://github.com/opencv/opencv/pull/17134

**Comment by fischermario** [comment]
@alalek: Thank you. I will patch OpenCV 4.3.0 with the changes from the pull request and report back.

**Comment by fischermario** [comment]
@alalek: The patch solves the issue entirely :blush: Thanks again! Will there be a patch release for the OpenCV 4.3.x series?

**Comment by ilya-lavrenov** [comment]
@fischermario is the issue resolved? can be closed?

**Comment by s-t-e-p-a-n-o-v** [comment]
> 
> 
> @fischermario is the issue resolved? can be closed?

Nop, mensioned patch for opencv https://github.com/opencv/opencv/pull/17134 is already included in opencv-4.3-openvino-2020.3 release
https://github.com/opencv/opencv/tree/4.3.0-openvino-2020.3.0/modules/dnn/src
dnn.cpp and test_ie_models.cpp

Just tested on openvino 2020.3 and opencv 4.3.0-openvino-2020.3 on ARM64 target:
Models from here https://download.01.org/opencv/2019/open_model_zoo/R3/20190905_163000_models_bin/ works, but fresh models from here https://download.01.org/opencv/2020/openvinotoolkit/2020.3/open_model_zoo/models_bin/1/ doesn't work.

Same error: 
cv2.error: OpenCV(4.3.0-openvino-2020.3.0) /home/ubuntu/opencv-4.3.0-openvino-2020.3.0/modules/dnn/src/op_inf_engine.cpp:881: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = MYRIAD): Unexpected CNNNetwork format: it was converted to deprecated format prior plugin's call in function 'initPlugin'

**Comment by dkurt** [comment]
@s-t-e-p-a-n-o-v, Can you please try to test the latest master branch of OpenCV?

**Comment by s-t-e-p-a-n-o-v** [comment]
I tried without success with 4.4.0-pre

There was build error:
[ 76%] Linking CXX executable ../../bin/opencv_perf_dnn
/usr/bin/ld: /home/aaa/openvino/bin/aarch64/Release/lib//libinference_engine_s.a(ie_core.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.17'
/usr/lib/gcc/aarch64-linux-gnu/7/../../../aarch64-linux-gnu/libdl.so: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
modules/dnn/CMakeFiles/opencv_perf_dnn.dir/build.make:175: recipe for target 'bin/opencv_perf_dnn' failed
make[2]: *** [bin/opencv_perf_dnn] Error 1
CMakeFiles/Makefile2:2328: recipe for target 'modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all' failed
make[1]: *** [modules/dnn/CMakeFiles/opencv_perf_dnn.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

I created separate issue for this - https://github.com/openvinotoolkit/openvino/issues/1221

**Comment by s-t-e-p-a-n-o-v** [comment]
Issue #1221 (libinference_engine_s.a(ie_core.cpp.o): undefined reference to symbol 'dlsym@@GLIBC_2.17') was resolved (remove libinference_engine*.a (libinference_engine_preproc_s.a and libinference_engine_s.a) files from openvino folder (/home/ubuntu/openvino/bin/aarch64/Release/lib)).
And now inference of IR10 models works as expected (at least for opencv 4.4-pre + openvino 2020.4)
