### PR TITLE
[core] Remove custom ov::optional

### PR DESCRIPTION
**Pull request by oToToT**
### Description:
As CPP17 is the default standard of OpenVINO, there is no need to use the self-implemented optional struct.

Note: discussed in https://github.com/openvinotoolkit/openvino/pull/28942.

### Related PRs:
- #28942

### CODE REVIEW

**Comment by praasz** [comment]
build_jenkins

**Comment by mlukasze** [comment]
build_jenkins

**Comment by oToToT** [comment]
Fixed the build on Ubuntu24.04.

Found that the bool operator of ov::optional is not marked as explicit while std::optional is.

**Comment by mlukasze** [comment]
build_jenkins

**Comment by oToToT** [comment]
can't see jenkins failure. do i need to do anything?

**Comment by praasz** [comment]
> can't see jenkins failures logs. do i need to do anything?

There are just build error which should be visible during standard local build of project.
```
 In file included from openvino/src/core/src/op/segment_max.cpp:10:

[2025-02-14T05:54:40.407Z] openvino/src/core/shape_inference/include/segment_max_shape_inference.hpp: In function ‘std::vector<UserT> ov::op::v16::shape_infer(const ov::op::v16::SegmentMax*, const std::vector<TShape>&, const ov::ITensorAccessor&)’:

[2025-02-14T05:54:40.408Z] openvino/src/core/shape_inference/include/segment_max_shape_inference.hpp:54:60: error: ‘optional’ is not a member of ‘ov’; did you mean ‘std::optional’?
```

**Comment by oToToT** [comment]
Thanks for sharing the error message. It seems like these are some file not in my forked branch but in the latest trunk.

I've rebased and updated those files to reflect the removal of `ov::optional`.

**Comment by praasz** [comment]
build_jenkins

**Comment by mlukasze** [comment]
build_jenkins

**Review by praasz — APPROVED** [review]

**Comment by mlukasze** [comment]
@itikhono please take a look, it's ready to merge, but would prefer to have your approval as well

**Review by dmitry-gorokhov — APPROVED** [review]
CPU part LGTM

**Review by itikhono — APPROVED** [review]

**Comment by oToToT** [comment]
rebased and fixed the merge conflict

**Comment by mlukasze** [comment]
build_jenkins

**Comment by mlukasze** [comment]
image

**Comment by oToToT** [comment]
> image

oops. apologize for that. It should be fixed now. 

I've just built the code myself again to check it now.

**Comment by mlukasze** [comment]
build_jenkins

**Comment by mlukasze** [comment]
CI reported problem with clang-format, but that one is on us, do not change anything for now, please.
We will rebase and restart CI as soon as problem will be solved by our teams

**Comment by mlukasze** [comment]
no problem, as rebase is done I will run CI as soon as we will have confirmation that problem has been solved.
stay tuned

**Comment by mlukasze** [comment]
build_jenkins
