### ISSUE TITLE
Converting DLRM (Onnx) to Intermediate Representation Format (IR)

### ISSUE THREAD

**Issue by jdc711** [openvinotoolkit/openvino#9787]
####################################
Question: I am trying to convert Facebook's DLRM model from onnx form into IR form, but I am running into errors (the error is shown at the very bottom). Thank you so much for your support.
####################################
Logistics:
-CPU used, I am using 2.6 GHz 6-Core Intel Core i7, for Macbook pro. 
####################################
Steps to reproduce issue: 
The dlrm model can be downloaded from:
"https://github.com/facebookresearch/dlrm". After downloading, you can move to the main folder/directory "dlrm-main", and then run the command "python3 dlrm_s_pytorch --save-onnx". This will create the onnx file, named "dlrm_s_pytorch.onnx".
Then, I run "mo.py --input_model dlrm_s_pytorch.onnx --log_level=DEBUG"
####################################
The error:
python3 /../../../opt/intel/openvino_2021.4.689/deployment_tools/model_optimizer/mo.py --input_model dlrm_s_pytorch.onnx                  
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/Users/dongwoo/Desktop/dlrm-main/dlrm_s_pytorch.onnx
	- Path for generated IR: 	/Users/dongwoo/Desktop/dlrm-main/.
	- IR output name: 	dlrm_s_pytorch
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
ONNX specific parameters:
	- Inference Engine found in: 	/usr/local/lib/python3.7/site-packages/openvino
Inference Engine version: 	2021.4.2-3976-0943ed67223-refs/pull/539/head
Model Optimizer version: 	2021.4.1-3926-14e67d86634-releases/2021/4
[ WARNING ] Model Optimizer and Inference Engine versions do no match.
[ WARNING ] Consider building the Inference Engine Python API from sources or reinstall OpenVINO (TM) toolkit using "pip install openvino==2021.4"
[ WARNING ]  Convert data type of Parameter "offsets" to int32
[ WARNING ]  Convert data type of Parameter "indices_0" to int32
[ WARNING ]  Convert data type of Parameter "indices_1" to int32
[ WARNING ]  Convert data type of Parameter "indices_2" to int32
[ ERROR ]  Shape [-1  3] is not fully defined for output 0 of "Gemm_0". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "Gemm_0".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "Gemm_0". 
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Elementwise.__init__.<locals>.<lambda> at 0x13e847950>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Gemm_0" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by jgespino** [comment]
Hi @jdc711 

I ran into the same error when converting the model using OpenVINO 2021.4.2 release. However, this may have already been addressed as I am able to convert and load the model to CPU using OpenVINO from Master Branch (8ebe75f81a4bde48c3827ea0a3005f0ea6f8f031).

Could you try [building](https://github.com/openvinotoolkit/openvino/wiki/BuildingCode) OpenVINO from source and see if it works for you too?

```
mo --input_model dlrm_s_pytorch.onnx
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/home/pse/Downloads/dlrm/dlrm_s_pytorch.onnx
	- Path for generated IR: 	/home/pse/Downloads/dlrm/.
	- IR output name: 	dlrm_s_pytorch
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Source layout: 	Not specified
	- Target layout: 	Not specified
	- Layout: 	Not specified
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
	- Use legacy API for model processing: 	False
	- Use the transformations config file: 	None
	- OpenVINO runtime found in: 	/opt/intel/openvino_2022/python/python3.6/openvino
OpenVINO runtime version: 	custom_master_8ebe75f81a4bde48c3827ea0a3005f0ea6f8f031
Model Optimizer version: 	custom_master_8ebe75f81a4bde48c3827ea0a3005f0ea6f8f031
[ WARNING ]  The version checker doesn't support environment marker combination and it will be ignored:  python_version < "3.8" and sys_platform == "win32"
[ ERROR ]  Error happened while importing openvino-telemetry module. It may happen due to unsatisfied requirements of that module. Please run requirements installation script once more.
Details on module importing failure: invalid syntax (<string>, line 1)
[ WARNING ]  
Detected not satisfied dependencies:
	tensorflow: installed: 1.15.5, required: ~= 2.5.0
	mxnet: installed: 1.7.0, required: ~= 1.7.0.post2
	networkx: installed: 2.5.1, required: ~= 2.6
	openvino-telemetry: package error, required: >= 2022.1.0

Please install required versions of components or use install_prerequisites script
/usr/local/lib/python3.6/dist-packages/openvino/tools/mo/install_prerequisites/install_prerequisites.sh
Note that install_prerequisites scripts may install additional components.
[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/pse/Downloads/dlrm/dlrm_s_pytorch.xml
[ SUCCESS ] BIN file: /home/pse/Downloads/dlrm/dlrm_s_pytorch.bin
[ SUCCESS ] Total execution time: 2.32 seconds. 
[ SUCCESS ] Memory consumed: 378 MB. 
```

Regards,
Jesus

**Comment by jdc711** [comment]
Hi,

Thanks for your reply. I have tried downloading the source code from https://github.com/openvinotoolkit/openvino/wiki/BuildingCode; however,  now I am having trouble finding the "mo" folder or any mo.py file within the entire directory. Do you think you can help me with this? Thanks

Best,

Josh

**Comment by jdc711** [comment]
Thank you for your reply. I tried rebuilding from the source https://github.com/openvinotoolkit/openvino/wiki/BuildingCode for MACos, and I tried running python3 mo.py --input_model dlrm_s_pytorch.onnx. However, I am running into this error: "ERROR:root:No module named 'openvino.tools'
ERROR:root:Could not find the Inference Engine or nGraph Python API.
Consider building the Inference Engine and nGraph Python APIs from sources or try to install OpenVINO (TM) Toolkit using "install_prerequisites.sh".  

Would you be able to help me with this issue? Thank you

**Comment by jdc711** [comment]
Hi, thanks for your reply. Here are the stepps I have done so far:
1) I have recloned the git from :https://github.com/openvinotoolkit/openvino.git 
2) then I followed the steps to build for Mac osx here: https://github.com/openvinotoolkit/openvino/wiki/BuildingForMacOS

Now, what should I do next? Below is what I tried to do, but to no avail:
3) Then, I went to openvino/tools/mo directory, then ran python3 setup.py
4) Then, I ran ./install_prerequisites/install_prerequisites.sh

Then I got this error that says It cant find module "openvino.tools":
Traceback (most recent call last):
  File "/Users/dongwoo/Desktop/openvino/tools/mo/install_prerequisites/../openvino/tools/mo/utils/extract_release_version.py", line 6, in <module>
    from version import extract_release_version, get_version
  File "/Users/dongwoo/Desktop/openvino/tools/mo/openvino/tools/mo/utils/version.py", line 9, in <module>
    from openvino.tools.mo.utils.utils import get_mo_root_dir
ModuleNotFoundError: No module named 'openvino.tools'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dongwoo/Desktop/openvino/tools/mo/install_prerequisites/../openvino/tools/mo/utils/extract_release_version.py", line 8, in <module>
    from openvino.tools.mo.utils.version import extract_release_version, get_version
ModuleNotFoundError: No module named 'openvino.tools'
[ WARNING ] Failed to import OpenVINO Python API in: PYTHONPATH
[ WARNING ] cannot import name 'apply_moc_transformations' from 'openvino.offline_transformations' (/usr/local/lib/python3.7/site-packages/openvino/offline_transformations/__init__.py)
	- OpenVINO runtime found in: 	/Users/dongwoo/Desktop/openvino/bin/intel64/Release/lib/python_api/python3.7/openvino
OpenVINO runtime version: 	custom_master_5fe10299ab711798f046cae530164bf2ee32132f
Model Optimizer version: 	2022.1.custom_master_5fe10299ab711798f046cae530164bf2ee32132f
[ WARNING ] Model Optimizer and OpenVINO runtime versions do no match.
[ WARNING ] Consider building the OpenVINO Python API from sources or reinstall OpenVINO (TM) toolkit using "pip install openvino==2022.1"

[WARNING] All Model Optimizer dependencies are installed globally.
[WARNING] If you want to keep Model Optimizer in separate sandbox
[WARNING] run install_prerequisites.sh "{caffe|tf|tf2|mxnet|kaldi|onnx}" venv
           
Please help me with this issue. Thanks

**Comment by jdc711** [comment]
Another thing I noticed is that I cannot find "mo.py" in openvino/build/tools/mo
The only contents of this directory are .cmake filles and Makefile...

**Comment by jdc711** [comment]
Thanks for your reply, @jgespino. I tried recloning from the master branch, and then running "mo --input_model dlrm_s_pytorch.onnx". However, I am still running into this error: dongwoo@Joshuas-MacBook-Pro-3 build % mo --input_model dlrm_s_pytorch.onnx 
[ WARNING ] Telemetry will not be sent as TID is not specified.
Model Optimizer arguments:
Common parameters:
	- Path to the Input Model: 	/Users/dongwoo/Desktop/openvino/build/dlrm_s_pytorch.onnx
	- Path for generated IR: 	/Users/dongwoo/Desktop/openvino/build/.
	- IR output name: 	dlrm_s_pytorch
	- Log level: 	ERROR
	- Batch: 	Not specified, inherited from the model
	- Input layers: 	Not specified, inherited from the model
	- Output layers: 	Not specified, inherited from the model
	- Input shapes: 	Not specified, inherited from the model
	- Mean values: 	Not specified
	- Scale values: 	Not specified
	- Scale factor: 	Not specified
	- Precision of IR: 	FP32
	- Enable fusing: 	True
	- Enable grouped convolutions fusing: 	True
	- Move mean values to preprocess section: 	None
	- Reverse input channels: 	False
ONNX specific parameters:
	- Inference Engine found in: 	/usr/local/lib/python3.7/site-packages/openvino
Inference Engine version: 	2021.4.2-3976-0943ed67223-refs/pull/539/head
Model Optimizer version: 	2021.4.2-3976-0943ed67223-refs/pull/539/head
[ WARNING ] Telemetry will not be sent as TID is not specified.
[ WARNING ]  Convert data type of Parameter "offsets" to int32
[ WARNING ]  Convert data type of Parameter "indices_0" to int32
[ WARNING ]  Convert data type of Parameter "indices_1" to int32
[ WARNING ]  Convert data type of Parameter "indices_2" to int32
[ ERROR ]  Shape [-1  3] is not fully defined for output 0 of "Gemm_0". Use --input_shape with positive integers to override model input shapes.
[ ERROR ]  Cannot infer shapes or values for node "Gemm_0".
[ ERROR ]  Not all output shapes were inferred or fully defined for node "Gemm_0". 
 For more information please refer to Model Optimizer FAQ, question #40. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=40#question-40)
[ ERROR ]  
[ ERROR ]  It can happen due to bug in custom shape infer function <function Elementwise.__init__.<locals>.<lambda> at 0x110f0d170>.
[ ERROR ]  Or because the node inputs have incorrect values/shapes.
[ ERROR ]  Or because input shapes are incorrect (embedded to the model or passed via --input_shape).
[ ERROR ]  Run Model Optimizer with --log_level=DEBUG for more information.
[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 'extensions.middle.PartialInfer.PartialInfer'>): Stopped shape/value propagation at "Gemm_0" node. 
 For more information please refer to Model Optimizer FAQ, question #38. (https://docs.openvinotoolkit.org/latest/openvino_docs_MO_DG_prepare_model_Model_Optimizer_FAQ.html?question=38#question-38)

**Comment by zulkifli-halim** [comment]
Hello @jdc711, I'm able to convert the dlrm_s_pytorch model to IR.

[ SUCCESS ] Generated IR version 11 model.
[ SUCCESS ] XML file: /home/user/openvino/tools/mo/dlrm_s_pytorch.xml
[ SUCCESS ] BIN file: /home/user/openvino/tools/mo/dlrm_s_pytorch.bin
[ SUCCESS ] Total execution time: 15.27 seconds.
[ SUCCESS ] Memory consumed: 343 MB.

You can clone the OpenVINO repository from this branch:
[https://github.com/openvinotoolkit/openvino/tree/8ebe75f81a4bde48c3827ea0a3005f0ea6f8f031](https://github.com/openvinotoolkit/openvino/tree/8ebe75f81a4bde48c3827ea0a3005f0ea6f8f031)

Then you can follow the steps from [here ](https://www.intel.com/content/www/us/en/support/articles/000057448/software/development-software.html)to build OpenVINO from Source.

**Comment by jdc711** [comment]
Hi @zulkifli-halim , thanks for your reply. I tried using the same branch but I am stilll getting the same error... Are you using a Mac?

**Comment by jdc711** [comment]
@jgespino in my error, it keeps saying there is an input shape with a negative value... do you possibly know why this is happening?

**Comment by jgespino** [comment]
HI @jdc711 

The mo version you are using doesn't seem to be from the master branch.
```
Inference Engine version: 2021.4.2-3976-0943ed67223-refs/pull/539/head
Model Optimizer version: 2021.4.2-3976-0943ed67223-refs/pull/539/head
```

After I built OpenVINO from source, I removed any previous versions of mo and re-installed from the built package using the following commands.
```
pip3 uninstall openvino
pip3 uninstall openvino-dev

cd <openvino source>/tools/mo
python3 setup.py install
source /opt/intel/openvino_2022/setupvars.sh

mo --version
Version of Model Optimizer is:
custom_master_6f60a7d8f098c7cf3195ba96d964a11bf1babe55
```

By the way, in my cmake command I added `-DCMAKE_INSTALL_PREVIX=/opt/intel/openvino_2022` and ran `make install` after the built finished.

Please also share your onnx model for me to test on my side.

Regards,
Jesus

**Comment by jdc711** [comment]
@jgespino Thanks for your reply. I will try reinstalling with your steps and update you when Im done. Thanks. Here is a link to the repository where I uploaded the dlrm_s_pytorch.onnx file: https://github.com/jdc711/dlrm_onnx

**Comment by jdc711** [comment]
Also, @jgespino if you do not mind,   may I see the exact cmake command that you ran before running make ?

**Comment by jgespino** [comment]
Hi @jdc711 

The model linked above converted on my built from master branch. 

This is my CMake command:
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_PYTHON=ON -DPYTHON_EXECUTABLE=/usr/bin/python3.6 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so -DPYTHON_INCLUDE_DIR=/usr/include/python3.6 -DCMAKE_INSTALL_PREFIX=/opt/intel/openvino_2022 ..
```

I have Python 3.6, make sure to update the paths for your python version and location.

Regards,
Jesus

**Comment by jdc711** [comment]
@jgespino Hi, for some strange reason, I am not able to builld the code anymore. When I run make installl, I keep getting this error during the make:

[ 87%] Building CXX object src/plugins/intel_cpu/CMakeFiles/ov_intel_cpu_plugin.dir/src/nodes/mkldnn_multiclass_nms.cpp.o
[ 87%] Building CXX object src/plugins/intel_cpu/CMakeFiles/ov_intel_cpu_plugin.dir/src/nodes/mkldnn_mvn_node.cpp.o
/Users/dongwoo/Desktop/openvino/src/plugins/intel_cpu/src/nodes/mkldnn_mvn_node.cpp:83:37: error: self-comparison always evaluates to true [-Werror,-Wtautological-compare]
             mvnAttrs.planar_layout == mvnAttrs.planar_layout;
                                    ^
1 error generated.
make[2]: *** [src/plugins/intel_cpu/CMakeFiles/ov_intel_cpu_plugin.dir/src/nodes/mkldnn_mvn_node.cpp.o] Error 1
make[1]: *** [src/plugins/intel_cpu/CMakeFiles/ov_intel_cpu_plugin.dir/all] Error 2
make: *** [all] Error 2

**Comment by jgespino** [comment]
I will try to build on a Mac, could you tell me more about your environment?

- Mac OS Version
- Python Version
- CMake Version
- Clang Version

Regards,
Jesus

**Comment by jdc711** [comment]
@jgespino Sorry for the late reply, and thanks for your continued support. Here are my specs:

Mac OS Version: 11.6.2
Python Version: 3.7.12
CMake Version: 3.21.4
Clang Version: Apple clang version 13.0.0 (clang-1300.0.29.30)

**Comment by jdc711** [comment]
@jgespino meanwhile, would you also be able to share the xml and bin files you were successful able to generate?

**Comment by jgespino** [comment]
Hi @jdc711 

> would you also be able to share the xml and bin files you were successful able to generate?

I could share it but it would not work on OpenVINO 2021.4.2 release as the model needs to use the same version for the Inference Engine and the Model Optimizer.

I just got access to a Mac Mini but it only goes up to Mac OS 10.15, I will give it a try and let you know the outcome. 

Regards,
Jesus

**Comment by jdc711** [comment]
@jgespino Thank you so much

**Comment by jdc711** [comment]
@jgespino Great, thanks. I repodruced your steps and the cmake command worked, I think. I just wanted to confirm what your exact make command was (after cmake)?

**Comment by jgespino** [comment]
@jdc711 I just ran `make -j2`, modify the number of jobs depending on the number of available CPU cores/threads.

**Comment by jdc711** [comment]
<img width="1139" alt="Screen Shot 2022-02-03 at 12 34 30 PM" src="https://user-images.githubusercontent.com/44274490/152424321-2b6a090a-4146-4e83-9d04-6335d955e741.png">
Hi @jgespino , I have gotten closer than ever by reporducing your steps. While I have succesfully created the xml and bin file, the program crashes with a seg fault as shown in the picture. IS that okay?

**Comment by jdc711** [comment]
Also, how do I run the benchmark inference engine on the xml and bin files?

**Comment by jgespino** [comment]
Hi @jdc711 

I didn't see a segmentation fault when converting the model on my end. To run the benchmark_app, you can use the python script in openvino_source/tools/benchmark_tools. You will need to export a couple of variables first:
```
export PYTHONPATH=$PYTHONPATH:~/openvino_source/bin/intel64/Release/lib/python_api/python3.7
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/openvino_source/bin/intel64/Release/lib/
```

I ran into an issue, not sure if it's on the master branch or my environment. 

However, I tried using the [2022.1 development package](https://github.com/openvinotoolkit/openvino/releases/tag/2022.1.0.dev20220131) we just released and it may be a faster option for you to test your model. I recommend using the pip method to install as it's fairly straight forward.

```
python3 -m pip install --user virtualenv 
python3 -m venv openvino_env_dev
source openvino_env_dev/bin/activate
python3 -m pip install --upgrade pip
pip install openvino-dev==2022.1.0.dev20220131
mo --input_model dlrm_s_pytorch.onnx
benchmark_app -m dlrm_s_pytorch.xml
```

Note, on the benchmark_app you will need to specify the input shapes as the model has dynamic inputs.

Regards,
Jesus

**Comment by jdc711** [comment]
May I ask, I am not sure how to specify the input shapes for the command. IF you were to do this command, how would you write the entire command?

**Comment by jgespino** [comment]
Hi @jdc711 

I'm not familiar with the model to determine the input shape. I recommend looking at the model's documentation to determine the expected input. You can also try to visualize the model using Netron or similar tool to see if that helps. 

Regards,
Jesus

**Comment by jdc711** [comment]
@jgespino Hi, this is the input format for the DLRM, as outputted by the default code at the very bottom of the entire dlrm_s_pytorch.py file:

"Finished training it 1/1 of epoch 0, -1.00 ms/it, loss 0.083850
X_onnx.shape torch.Size([1, 4])
lS_o_onnx.shape torch.Size([3, 1])
ii.shape torch.Size([3])
ii.shape torch.Size([1])
ii.shape torch.Size([1])
inputs ['dense_x', 'offsets', 'indices_0', 'indices_1', 'indices_2']
{'dense_x': {0: 'batch_size'}, 'pred': {0: 'batch_size'}, 'offsets': {1: 'batch_size'}, 'indices_0': {0: 'batch_size'}, 'indices_1': {0: 'batch_size'}, 'indices_2': {0: 'batch_size'}}"

How would I input this as the dynamic input for the benchmark_app command?

**Comment by jdc711** [comment]
<img width="684" alt="Screen Shot 2022-02-04 at 2 58 27 PM" src="https://user-images.githubusercontent.com/44274490/152614260-9ec196d3-c448-4a57-b854-b97974517423.png">
@jgespino Here is the code that converts the dlrm into onnx w the specific input names shown. I apologize, but I am not experienced enough with openvino to figure out the command for ruunning with the dynamic input names of the dlrm. If possible, would you be able to help me with running this command? Thank you.

**Comment by jdc711** [comment]
@jgespino 
Hi, Thanks so much for your help. I was able to run the inference on CPU. Thanks. However, when I tried to run inference on the MYRIAD stick, it did not work becuase I did not have the MYRIAD plug in:
" ERROR ] Cannot load library 'libov_intel_myriad_plugin.so: dlopen(libov_intel_myriad_plugin.so, 2): image not found
Traceback (most recent call last):
  File "/Users/dongwoo/Desktop/openvino/build/openvino_env_dev/lib/python3.7/site-packages/openvino/tools/benchmark/main.py", line 85, in run
    supported_config_keys = benchmark.core.get_metric(device, 'SUPPORTED_CONFIG_KEYS')
RuntimeError: Cannot load library 'libov_intel_myriad_plugin.so: dlopen(libov_intel_myriad_plugin.so, 2): image not found'

How do I install this plug in?

**Comment by jdc711** [comment]
@jgespino Hi, were you possibly able to figure out this MYRIAD NC2 stick error?

**Comment by jdc711** [comment]
Thanks @jgespino 

I see. Would there be any way I can run the DLRM on the MYRIAD NCS2 stick? My main project goal was to run the DLRM on 1) CPU and on 2)MYRIAD NCS2 stick, and then compare the execution times for both.

**Comment by avitial** [comment]
@jdc711 looks like this DLRM model contains Loop ops which are currently not supported by Myriad plugin:

![image](https://user-images.githubusercontent.com/20826577/155236092-e5ef5cb0-e428-49c9-870a-3d7e896d7929.png)

I went ahead and did a quick test on master branch anyways, and the model cannot execute successfully on Myriad plugin which is expected.

`RuntimeError: [ GENERAL_ERROR ]
/home/jenkins/agent/workspace/private-ci/ie/build-linux-ubuntu18/b/repos/openvino/src/plugins/intel_vpu/common/src/ngraph/transformations/dynamic_to_static_shape_loop.cpp:53 Encountered a loop v5::Loop 40 (39[0]:i64{}, 150[0]:boolean{}, 31[0]:i64{2}, 36[0]:i64{1}, Convert_504[0]:i64{1}) -> (f32{1,2}) with dynamic operation v1::StridedSlice 47 (Parameter_78[0]:i64{1}, 45[0]:i64{1}, 46[0]:i64{1}, Broadcast_66[0]:i64{1}) -> (i64{?}) in the body, but only static body loops are supported. 
`

**Comment by avitial** [comment]
Closing this, feel free to reopen and ask additional questions related to this topic.

**Comment by kekeblom** [comment]
@avitial I'm working with a model that has a Loop operation and would like to deploy it on Myriad. I can compile the model for CPU, where it works just right. However, when running the `compile_tool` with `-d MYRIAD`, I get the same error as above.

What would be required to add Loop operation support to the Myriad backend? Is it fundamentally not possible on the hardware, and the recommended course of action would be to modify the model such that it doesn't contain loops? Any other tips or recommendations?
