### PR TITLE
[Protopipe] Fix const reference binding in config parser

### PR DESCRIPTION
**Pull request by dbermond**
### Details:
 - *This fixes the following compile error, introduced by commit 64a330242e291e372e37f4344316deb63f6474fe:*
```
src/plugins/intel_npu/tools/protopipe/src/parser/config.cpp:148:9: error: cannot bind non-const lvalue reference of type ‘ConfigNode::KeyValueProxy&’ to an rvalue of type ‘ConfigNode::KeyValueProxy’
  148 |         for (auto& child : node) {
      |         ^~~
```

### Tickets:
 - *none*

### AI Assistance:
 - *AI assistance used: no*

### CODE REVIEW

**Comment by svigh** [comment]
Seems we missed this, thank you. On Visual Studio there was no compilation error, will need to look into that.

**Comment by dbermond** [comment]
> Seems we missed this, thank you. On Visual Studio there was no compilation error, will need to look into that.

This compile error showed when using GCC 15.2. Thank you for your review.

**Comment by svigh** [comment]
build_jenkins
