### ISSUE TITLE
Possible compatabiility issue with networkx 2.4

### ISSUE THREAD

**Issue by giangdao04** [openvinotoolkit/openvino#289]
**Description**:
While setting up OpenVINO inside docker, we notice that it fails to parse graph def. For some caffe models, the logs are like these
```
odel Optimizer version:        2019.3.0-375-g332562022
[ ERROR ]  -------------------------------------------------
[ ERROR ]  ----------------- INTERNAL ERROR ----------------
[ ERROR ]  Unexpected exception happened.
[ ERROR ]  Please contact Model Optimizer developers and forward the following information:
[ ERROR ]  'Graph' object has no attribute 'node'
[ ERROR ]  Traceback (most recent call last):
  File "openvino/model_optimizer/mo/main.py", line 302, in main
    return driver(argv)
  File "openvino/model_optimizer/mo/main.py", line 261, in driver
    custom_layers_mapping_path=custom_layers_mapping_path)
  File "openvino/model_optimizer/mo/pipeline/caffe.py", line 65, in driver
    graph, original_shapes = loader.caffe_pb_to_nx(proto, model)
  File "openvino/model_optimizer/mo/front/caffe/loader.py", line 252, in caffe_pb_to_nx
    kind='op')
  File "openvino/model_optimizer/mo/graph/graph.py", line 505, in add_node
    node.update_node()
  File "openvino/model_optimizer/mo/graph/graph.py", line 470, in update_node
    in_ports_count = self.in_ports_count if self.has_valid('in_ports_count') else None
  File "openvino/model_optimizer/mo/graph/graph.py", line 161, in has_valid
    return self.has(k) and not self.graph.node[self.node][k] is None
  File "openvino/model_optimizer/mo/graph/graph.py", line 158, in has
    return k in self.graph.node[self.node]
AttributeError: 'Graph' object has no attribute 'node'

[ ERROR ]  ---------------- END OF BUG REPORT --------------
[ ERROR ]  -------------------------------------------------
```
For Onnx models, the error logs are similar but shorter. It usually contains 'Graph' object has no attribute 'node' attribute error.

**To reproduce the error**:
- Download intel OpenVINO toolkit
- Copy the model optimizer to docker and install prerequisite. If the docker doesn't have any version of `networkx` installed, `networkx==2.4` will be installed
- Run model optimizer inside docker and see the errors

**Temporary solution**:
- Run `pip3 install networkx==2.3` to enforce 2.3 version of networkx

Maybe we can pin the version of networkx to prevent these kind of isuse?

**Comment by shubha-ramani** [comment]
@giangdao04 
This is a good point. Thanks for bringing it up. Somewhere we should "pin the version of networkx" by putting it in a requirements.txt somewhere.

I will file a bug on this issue. 

Again thanks for your suggestion !

Shubha

**Comment by thiagomacieira** [comment]
Please do not pin: maximum versions are not acceptable in Linux distributions. Just make it work with network 2.4.

DLDT is currently broken on Clear Linux until this issue is fixed and will remain broken until networkx 2.4 support is added.

**Comment by jgespino** [comment]
Closing issue, OpenVINO now uses Networkx version 2.5 per [requirements.txt](https://github.com/openvinotoolkit/openvino/blob/master/tools/mo/requirements.txt).
