### ISSUE TITLE
Building from the master/2020 branch fails due to unnecessary parentheses

### ISSUE THREAD

**Issue by psyhtest** [openvinotoolkit/openvino#462]
With [CK-OpenVINO](https://github.com/ctuning/ck-openvino/):
```bash
$ python3 -m pip install ck --user
$ ck pull repo:ck-openvino
$ ck install package --tags=lib,openvino,2020
...
In file included from /home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020-linux-64/obj/_deps/ext_onnx-src/onnx/defs/tensor/utils.h:6,
                 from /home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020-linux-64/obj/_deps/ext_onnx-src/onnx/defs/tensor/defs.cc:4:
/home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020-linux-64/obj/_deps/ext_onnx-src/onnx/defs/tensor/defs.cc: In lambda function:
/home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020-linux-64/obj/_deps/ext_onnx-src/onnx/defs/tensor/defs.cc:1363:22: error: unnecessary parentheses in declaration of ‘i’ [-Werror=parentheses]
           for (size_t(i) = 0; i < axes.size(); ++i) {
                      ^
/home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020-linux-64/obj/_deps/ext_onnx-src/onnx/defs/schema.h:901:12: note: in definition of macro ‘ONNX_OPERATOR_SET_SCHEMA_EX’
     return impl.SetName(#name)                                              \
            ^~~~
```

**Comment by alalek** [comment]
Looks like it is `-Werror` problem, check for similar issues.

**Comment by psyhtest** [comment]
It definitely is. It builds with GCC 7.4 which is less picky.

**Comment by psyhtest** [comment]
Same with the 2020.2 release, by the way:
```
/home/anton/CK_TOOLS/lib-openvino-gcc-8.3.0-2020.2-linux-64/obj/_deps/ext_onnx-src/onnx/defs/tensor/defs.cc:1363:22: error: unnecessary parentheses in declaration of ‘i’ [-Werror=parentheses]
           for (size_t(i) = 0; i < axes.size(); ++i) {
                      ^
```

**Comment by psyhtest** [comment]
Because the error is in `_deps/ext_onnx-src` can it be even disabled from the OpenVINO sources? If so, which of flags would do it?
```
anton@velociti:~/CK_TOOLS/lib-openvino-gcc-8.4.0-2020.2-linux-64/openvino$ grep Werror * -R
Binary file bin/intel64/Release/lib/libopencv_c_wraper.so matches
Binary file bin/intel64/Release/lib/libformat_reader.so matches
cmake/os_flags.cmake:    # ie_add_compiler_flags(-Werror)
cmake/os_flags.cmake:        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
inference-engine/src/vpu/common/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=unused-variable")
inference-engine/src/vpu/common/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=unused-function")
inference-engine/src/vpu/common/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=strict-aliasing")
inference-engine/src/vpu/graph_transformer/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=unused-variable")
inference-engine/src/vpu/graph_transformer/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=unused-function")
inference-engine/src/vpu/graph_transformer/CMakeLists.txt:        target_compile_options(${TARGET_NAME} PRIVATE "-Werror=strict-aliasing")
inference-engine/tests/ie_test_utils/common_test_utils/gtest/googletest/xcode/Config/General.xcconfig:WARNING_CFLAGS = -Wall -Werror -Wendif-labels -Wnewline-eof -Wno-sign-compare -Wshadow
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      GROUP NAME TreatWarnAsError   "-Werror|-pedantic-errors"
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      ALIAS TreatWarnAsErrorEnabled    "-Werror" "-pedantic-errors"
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      GROUP NAME TreatWarnAsError   "-Werror|-pedantic-errors"
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      ALIAS TreatWarnAsErrorEnabled    "-Werror" "-pedantic-errors"
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      GROUP NAME TreatWarnAsError   "-Werror"
inference-engine/thirdparty/clDNN/CMakeCompilerLinkerOpts.txt:      ALIAS TreatWarnAsErrorEnabled    "-Werror"
inference-engine/thirdparty/mkl-dnn/cmake/platform.cmake:    append_if(MKLDNN_WERROR CMAKE_CCXX_FLAGS "-Werror")
inference-engine/samples/CMakeLists.txt:        set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror") #treating warnings as errors
Binary file inference-engine/temp/omp/lib/libiomp5.so matches
ngraph/cmake/clang_4_0_flags.cmake:set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=return-type")
ngraph/cmake/clang_4_0_flags.cmake:set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=inconsistent-missing-override")
ngraph/cmake/clang_4_0_flags.cmake:set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror=comment")
ngraph/CMakeLists.txt:    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Werror")
```

**Comment by ilya-lavrenov** [comment]
@psyhtest you can compile OpenVINO with `cmake -DNGRAPH_ONNX_IMPORT_ENABLE=OFF`
