### ISSUE TITLE
[Bug] Cannot run inference on OpenVino CPU after update to OpenVino 2022.2

### ISSUE THREAD

**Issue by JulienMaille** [openvinotoolkit/openvino#13493]
##### System information (version)
- OpenVINO => 2022.2
- Operating System / Platform => Windows 64 Bit
- Compiler => Visual Studio 2022
- Problem classification: Model Inference
- Framework: onnx infered through OpenCV
- Model name: Unet/ResNet

##### Detailed description
Copy of https://github.com/opencv/opencv/issues/22640

We've been inferring a resnet based dnn for years using OpenCV, with support for different backends.
Recently, after upgrading to OpenVino 2022.2 and recompiling OpenCV 4.6 we have an exception when inferring on several Intel CPUs (one i9-gen10, one i5-gen8) (it works on Intel GPUs):
`Exception: OpenCV(4.6.0-dev) D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp:747: error: (-2:Unspecified error) Failed to initialize Inference Engine backend (device = CPU): Cannot get memory! in function 'cv::dnn::InfEngineNgraphNet::initPlugin'`

This might be a bug for https://github.com/openvinotoolkit/openvino/ as the exception is trigger here:
https://github.com/opencv/opencv/blob/347246901eccabe503985a64f16813ca859af25a/modules/dnn/src/ie_ngraph.cpp#L1070
but with a message from
https://github.com/openvinotoolkit/openvino/blob/042bd7274ac36715e16386be5c1f17924d53dede/src/plugins/intel_cpu/src/cpu_memory.h#L206

##### Issue submission checklist

 - [x] I report the issue, it's not a question
 - [x] I checked the problem with documentation, FAQ, open issues, Stack Overflow, etc and have not found solution
 - [x] There is reproducer code and related data files: images, videos, models, etc.

**Comment by JulienMaille** [comment]
@dmitry-gorokhov for additional information, I'm inferring on dynamic shapes

**Comment by dmitry-gorokhov** [comment]
Hi @JulienMaille, sorry for the late response. I asked the team to take a look on the issue. Will get back soon.

**Comment by yuxu42** [comment]
@JulienMaille could you please provide more information for us to analyze the issue?
1) could you please share the test case to reproduce the issue?
2) could you please share the model?
3) does it work with the combination of opencv4.6 and openvino 2022.1?

**Comment by JulienMaille** [comment]
1/2. I invited you to a private repository with the inference code and a model that reproduce the issue. You just need to run `inference.exe models/test1.onnx`

3. Here the difference between 2022.1.1 and 2022.2.0
```
OpenCV version: 4.6.0-dev
Generating image [256,256]..done
[ INFO:0@0.451] global D:\Dev\opencv\modules\core\src\ocl.cpp (1186) cv::ocl::haveOpenCL Initialize OpenCL runtime...
[ INFO:0@0.467] global D:\Dev\opencv\modules\core\src\ocl.cpp (1192) cv::ocl::haveOpenCL OpenCL: found 1 platforms
[ INFO:0@0.467] global D:\Dev\opencv\modules\core\src\ocl.cpp (984) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: initializing thread execution context
[ INFO:0@0.467] global D:\Dev\opencv\modules\core\src\ocl.cpp (994) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: creating new execution context...
[ INFO:0@0.569] global D:\Dev\opencv\modules\core\src\ocl.cpp (1012) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: device=NVIDIA GeForce RTX 3080 Ti
 == Running first inference on BACKEND_OPENVINO-TARGET_CPU ==
[ INFO:0@0.611] global D:\Dev\opencv\modules\dnn\src\onnx\onnx_importer.cpp (822) cv::dnn::dnn4_v20220524::ONNXImporter::populateNet DNN/ONNX: loading ONNX v6 model produced by 'pytorch':1.8. Number of nodes = 63, initializers = 52, inputs = 1, outputs = 1
[ INFO:0@0.611] global D:\Dev\opencv\modules\dnn\src\onnx\onnx_importer.cpp (738) cv::dnn::dnn4_v20220524::ONNXImporter::parseOperatorSet DNN/ONNX: ONNX opset version = 12
Loading model..done in 77ms
[ INFO:0@0.687] global D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp (130) cv::dnn::detectArmPlugin_ CPU plugin: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
[ INFO:0@0.734] global D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp (742) cv::dnn::InfEngineNgraphNet::initPlugin DNN/IE: Calling LoadNetwork(device=CPU)...
OpenCV(4.6.0-dev) Error: Unspecified error (> Failed to initialize Inference Engine backend (device = CPU):
> C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\plugins\intel_cpu\src\cpu_memory.h:206 Cannot get memory!
) in cv::dnn::InfEngineNgraphNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp, line 747
OpenCV(4.6.0-dev) D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp:747: error: (-2:Unspecified error) in function 'cv::dnn::InfEngineNgraphNet::initPlugin'
> Failed to initialize Inference Engine backend (device = CPU):
> C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\plugins\intel_cpu\src\cpu_memory.h:206 Cannot get memory!
Inference done in 1302ms
OpenCV(4.6.0-dev) Error: Assertion failed (data) in cv::Mat::at, file D:\Dev\opencv\bld-x64-msvc2022-cuda10.2-dnn8.5.0-vino2022.1.1\install\include\opencv2/core/mat.inl.hpp, line 897
```
```
[ INFO:0@0.396] global D:\Dev\opencv\modules\core\src\ocl.cpp (1192) cv::ocl::haveOpenCL OpenCL: found 1 platforms
[ INFO:0@0.396] global D:\Dev\opencv\modules\core\src\ocl.cpp (984) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: initializing thread execution context
[ INFO:0@0.396] global D:\Dev\opencv\modules\core\src\ocl.cpp (994) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: creating new execution context...
[ INFO:0@0.517] global D:\Dev\opencv\modules\core\src\ocl.cpp (1012) cv::ocl::OpenCLExecutionContext::Impl::getInitializedExecutionContext OpenCL: device=NVIDIA GeForce RTX 3080 Ti
 == Running first inference on BACKEND_OPENVINO-TARGET_CPU ==
[ INFO:0@0.556] global D:\Dev\opencv\modules\dnn\src\onnx\onnx_importer.cpp (822) cv::dnn::dnn4_v20220524::ONNXImporter::populateNet DNN/ONNX: loading ONNX v6 model produced by 'pytorch':1.8. Number of nodes = 63, initializers = 52, inputs = 1, outputs = 1
[ INFO:0@0.557] global D:\Dev\opencv\modules\dnn\src\onnx\onnx_importer.cpp (738) cv::dnn::dnn4_v20220524::ONNXImporter::parseOperatorSet DNN/ONNX: ONNX opset version = 12
Loading model..done in 79ms
[ INFO:0@0.635] global D:\Dev\opencv\modules\dnn\src\op_inf_engine.cpp (130) cv::dnn::detectArmPlugin_ CPU plugin: Intel(R) Core(TM) i9-10900X CPU @ 3.70GHz
[ INFO:0@0.687] global D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp (742) cv::dnn::InfEngineNgraphNet::initPlugin DNN/IE: Calling LoadNetwork(device=CPU)...
OpenCV(4.6.0-dev) Error: Unspecified error (> Failed to initialize Inference Engine backend (device = CPU):
> C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\plugins\intel_cpu\src\cpu_memory.h:204 Cannot get memory!
) in cv::dnn::InfEngineNgraphNet::initPlugin, file D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp, line 747
OpenCV(4.6.0-dev) D:\Dev\opencv\modules\dnn\src\ie_ngraph.cpp:747: error: (-2:Unspecified error) in function 'cv::dnn::InfEngineNgraphNet::initPlugin'
> Failed to initialize Inference Engine backend (device = CPU):
> C:\Jenkins\workspace\private-ci\ie\build-windows-vs2019\b\repos\openvino\src\plugins\intel_cpu\src\cpu_memory.h:204 Cannot get memory!
Inference done in 799ms
OpenCV(4.6.0-dev) Error: Assertion failed (data) in cv::Mat::at, file D:\Dev\opencv\bld-x64-msvc2022-cuda10.2-dnn8.5.0-vino2022.1.1\install\include\opencv2/core/mat.inl.hpp, line 897
```

**Comment by liubo-intel** [comment]
Hi, @JulienMaille :  could you please also add me to inference code repository? I'm trying to look into this issue together with @yuxu42 . 
BTW, if possible, could you please also add some description on how to reproduce this issue step by step(better including the ways how you build opencv and openvino in your inference code repository).
and from your previous log, it looks like both openvino 2022.2.0 and openvino 2022.1.1 failed in your case?

**Comment by JulienMaille** [comment]
@liubo-intel I have added you.
Yes it fails on both 2022.2.0 and 2022.1.1
In order to reproduce, you just need to use cmake to generate the project file with the desired version of opencv
Then compile it and run the exe, which takes a model in input.

**Comment by liubo-intel** [comment]
> @liubo-intel I have added you. Yes it fails on both 2022.2.0 and 2022.1.1 In order to reproduce, you just need to use cmake to generate the project file with the desired version of opencv Then compile it and run the exe, which takes a model in input. inference.exe, will try to infer on all available backends
> 
> ```
> $ mkdir build
> $ cd build
> $ cmake -G "Visual Studio 17 2022 Win64" -DOpenCV_DIR=[path_to_openCV_build_dir] ..
> $ cmake --build . --config Release
> $ Release/Inference.exe models/test1.onnx
> ```

@JulienMaille , thanks, I can access the repo now.  from opencv [build document](https://docs.opencv.org/4.x/db/d05/tutorial_config_reference.html) it looks like by default, when building opencv, 'WITH_OPENVINO' option is 'OFF'.
`WITH_OPENVINO	OFF	Enable Intel OpenVINO Toolkit support. Should be used for OpenVINO>=2022.1 instead of WITH_INF_ENGINE and WITH_NGRAPH.`
do you install your opencv from binary or building from source code? if from source code, could you please send me your opencv build option, then I can try to reproduce it with source code from my side.

**Comment by JulienMaille** [comment]
@liubo-intel I'm not recompiling OpenVino, I'm using the official packages. Although I also tried recompiling a special branch of OpenVino with a bug fix and still have the issue. In that case I had recompiled OpenVino with default options, using the supplied script.
Regarding OpenCV, I will upload my compilation script in the repository, but my options are something like this: `-DBUILD_LIST=core,imgcodecs,imgproc,highgui,photo,xphoto,dnn,cudev -DOPENCV_ENABLE_NONFREE=ON -DBUILD_TESTS=OFF -DOPENCV_EXTRA_MODULES_PATH=""../../opencv_contrib/modules"" -DENABLE_CXX11=ON -DBUILD_opencv_world=ON -DWITH_IMGCODEC_PXM=OFF -DWITH_IMGCODEC_PFM=OFF -DWITH_IMGCODEC_SUNRASTER=OFF -DWITH_IMGCODEC_HDR=OFF -DBUILD_JASPER=OFF -DWITH_JPEG=OFF -DWITH_JASPER=OFF -DWITH_TIFF=OFF -DWITH_FFMPEG=OFF -DWITH_GSTREAMER=OFF -DWITH_WEBP=OFF -DWITH_DSHOW=OFF -DWITH_OPENEXR=OFF -DWITH_MSMF=OFF -DWITH_AVFOUNDATION=OFF -DWITH_CUDA=ON -DWITH_CUDNN=ON -DOPENCV_DNN_CUDA=ON -DCUDA_ARCH_BIN=""$cuda_arch"" -DWITH_CUFFT=OFF -DWITH_CUBLAS=ON -DWITH_QUIRC=OFF -DWITH_INF_ENGINE=ON -DINF_ENGINE_RELEASE=$openvino_tag -DWITH_NGRAPH=ON -DCUDNN_LIBRARY=""$cudnn_lib"" -DCUDNN_INCLUDE_DIR=""$cudnn_include_folder"" -DCUDA_TOOLKIT_ROOT_DIR=""$cuda_toolkit"" -DWITH_PYTHON=OFF -DWITH_GSTREAMER=OFF -DWITH_OPENJPEG=OFF -DWITH_TESSERACT=OFF -DWITH_VTK=OFF -DWITH_WIN32UI=OFF -DWITH_DIRECTX=OFF -DWITH_ADE=OFF -DWITH_1394=OFF -DWITH_OPENCLAMDBLAS=OFF -DWITH_OPENCLAMDFFT=OFF -DWITH_OPENCL_D3D11_NV=OFF -DENABLE_FAST_MATH=ON -DCUDA_FAST_MATH=ON`

**Comment by liubo-intel** [comment]
@JulienMaille ： could you please have a try using '[4.5.5-openvino-2022.1.0](https://github.com/opencv/opencv/tree/4.5.5-openvino-2022.1.0)' tag version opencv compare with '[2022.1.0](https://github.com/openvinotoolkit/openvino/tree/2022.1.0)' tag version openvino, in order to get rid of openvino and opencv unmatched version reason. 
I've also tried this two version on my side. but meet some onnx import issues, I suspect it's my environment set up issues(trying to fix it). so could you please also have a try on your side?

**Comment by JulienMaille** [comment]
@liubo-intel I can try compiling that tag, what exactly is different there, it's not clear to me.

**Comment by liubo-intel** [comment]
> @liubo-intel I can try compiling that tag, what exactly is different there, it's not clear to me. That tag is from the 15th of February btw

@JulienMaille ，From My understanding opencv branch with "-openvino-XX" postfix stands for the opencv version which officially support openvino backend. and it needs to be used with compared openvino version "XX".
so, that means if you intend to use openvino backend in opencv, the recommend way is to select opencv versions with "-openvino-XX" postfix and select openvino with compared "XX" version.

**Comment by liubo-intel** [comment]
> @liubo-intel using `-DWITH_OPENVINO=ON` does not seems to work with this tag, do you confirm?
> 
> EDIT: so I noticed I had not commited the right .onnx file, this is fixed on the repository.
> 
> * Tag 4.4.5-openvion-2022.1.0 compiled with OpenVino 2022.1.1.7030 does work.
> * I will now test 4.4.5-openvion-2022.1.0 compiled with OpenVino 2022.2.0.7713 ... works too
> * Now testing opencv HEAD compiled with OpenVino 2022.2.0.7713 ... `Cannot get memory!` error

I think that make sense, recommend you use 'Tag 4.4.5-openvion-2022.1.0 compiled with OpenVino 2022.1.1.7030' for your current work. 'OpenVino 2022.2.0.7713' may need wait opencv team to upgrade opencv to the related version.

**Comment by JulienMaille** [comment]
@liubo-intel wouldn't we expect https://github.com/opencv/opencv/tree/master to work fine with OpenVino 2022.1.1 ?

**Comment by JulienMaille** [comment]
@liubo-intel do you know why there's no `4.6.x-openvino-2022.2.0` branch of OpenCV?

**Comment by yuxu42** [comment]
@alvoron Could you please help answer? Thanks!

**Comment by alvoron** [comment]
Since 2022.1.1 release OpenVINO team does not provide pre-built version of OpenCV and does not verify OpenVINO compatibility with the latest versions of OpenCV.
This instruction explains how to build OpenCV from source code against a specific version of OpenVINO: [link](https://github.com/opencv/opencv/wiki/BuildOpenCV4OpenVINO#approach-2-build-opencv-against-specific-version-of-openvino) 
If your OpenCV build procedure is similar to the one provided above, I'd suggest to raise a OpenCV ticket.

**Comment by liubo-intel** [comment]
> > I've also tried this two version on my side. but meet some onnx import issues, I suspect it's my environment set up issues(trying to fix it). so could you please also have a try on your side?
> 
> @liubo-intel were you able to use my reproducer?
> 
> @alvoron I already recompile OpenCV from source against OpenVino (and I've done this for months, it worked well until recently) A ticket was opened with [opencv/opencv#22640](https://github.com/opencv/opencv/issues/22640) first and they asked me to move it here.

@JulienMaille : I have also tried your test model "models/test1.onnx" by openvino internal [benchmark_app tool](https://github.com/openvinotoolkit/openvino/tree/master/tools/benchmark_tool) with version "OpenVino 2022.2":
`./benchmark_app -m ./models/test1.onnx -d CPU -hint tput -niter 10` 
it works fine without such memory issue. So it looks quite like that openvino(2022.2) CPU plugin support this model, but some issues happens when opencv integrate "OpenVino 2022.2" as its backend.

**Comment by JulienMaille** [comment]
@liubo-intel  I have been bisecting commits to find when it stops working and localized it to the changes made to `modules/dnn/src/onnx/onnx_importer.cpp` in this commit: https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd

More specifically, the problem is gone if I revert the replacement of 
https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L3797
`dispatch["Add"] = dispatch["Sum"] = dispatch["Sub"] = &ONNXImporter::parseBias;` with `&ONNXImporter::parseElementWise;`

**Comment by liubo-intel** [comment]
> @liubo-intel I have been bisecting commits to find when it stops working and localized it to the changes made to `modules/dnn/src/onnx/onnx_importer.cpp` in this commit: [opencv/opencv@ed69bca](https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd)
> 
> More specifically, the problem is gone if I revert the replacement of [opencv/opencv@ed69bca#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L3797](https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L3797) `dispatch["Add"] = &ONNXImporter::parseBias;` with `&ONNXImporter::parseElementWise;`

Hi, @tomdol : I'm not sure whether this 'onnx_importer' part is similar as openvino onnx part, could you please help have a quick look at this and give some suggestions if possible?

**Comment by yuxu42** [comment]
> @liubo-intel I have been bisecting commits to find when it stops working and localized it to the changes made to `modules/dnn/src/onnx/onnx_importer.cpp` in this commit: [opencv/opencv@ed69bca](https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd)
> 
> More specifically, the problem is gone if I revert the replacement of [opencv/opencv@ed69bca#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L3797](https://github.com/opencv/opencv/commit/ed69bcae2d171d9426cd3688a8b0ee14b8a140cd#diff-f9fc55b2657f441025bc0adfeb683491b1e3d8275702e159efcb368a1b2c0dd5L3797) `dispatch["Add"] = &ONNXImporter::parseBias;` with `&ONNXImporter::parseElementWise;`

@JulienMaille Thanks for the information! And with regards to what you've found in terms of the specific change about ONNX, it looks like the issue in OpenCV. Do you think it's proper to raise in OpenCV project?
And do you have any further question or problem about OpenVINO? Thanks!

**Comment by JulienMaille** [comment]
@yuxu42 The issue was initially raised with OpenCV and they redirected me here because the problem occurs in OpenVino GPU but not in OpenVino CPU. What do you think?

**Comment by yuxu42** [comment]
> 

@JulienMaille if you have no further questions about OpenVINO CPU or GPU, can I close the ticket?

**Comment by avitial** [comment]
Closing this, I hope previous responses were sufficient to help you proceed. Feel free to reopen and provide additional information or ask any questions related to this topic.
